# eng_facts_1.py — Vocabulary: synonyms (55), antonyms (45), spelling (30), idioms/one-word (40)
FACTS = [
# ---------------- SYNONYMS ----------------
("vocab",1,"Choose the synonym of IMMINENT:","Impending",["Distant","Immense","Eminent"],"Imminent = about to happen = impending. Don't confuse with 'eminent' (famous)."),
("vocab",2,"Choose the synonym of ACRIMONY:","Rancor",["Kindness","Harmony","Silence"],"Acrimony = bitterness/sharpness in speech = rancor."),
("vocab",1,"Choose the synonym of BENEVOLENT:","Kind",["Cruel","Selfish","Greedy"],"Benevolent = well-meaning and kindly."),
("vocab",1,"Choose the synonym of ABUNDANT:","Plentiful",["Scarce","Rare","Limited"],"Abundant = existing in large quantities = plentiful."),
("vocab",2,"Choose the synonym of CANDID:","Frank",["Deceptive","Secretive","Hesitant"],"Candid = truthful and straightforward = frank."),
("vocab",1,"Choose the synonym of DILIGENT:","Hardworking",["Lazy","Careless","Slow"],"Diligent = showing care and effort = hardworking."),
("vocab",2,"Choose the synonym of ELOQUENT:","Articulate",["Silent","Confused","Rude"],"Eloquent = fluent and persuasive in speech = articulate."),
("vocab",1,"Choose the synonym of FRAGILE:","Delicate",["Sturdy","Strong","Tough"],"Fragile = easily broken = delicate."),
("vocab",2,"Choose the synonym of GENUINE:","Authentic",["Fake","Artificial","Counterfeit"],"Genuine = real and authentic, not fake."),
("vocab",1,"Choose the synonym of HOSTILE:","Unfriendly",["Friendly","Warm","Welcoming"],"Hostile = showing opposition/unfriendliness."),
("vocab",2,"Choose the synonym of INEVITABLE:","Unavoidable",["Optional","Uncertain","Preventable"],"Inevitable = certain to happen = unavoidable."),
("vocab",1,"Choose the synonym of JOVIAL:","Cheerful",["Gloomy","Sad","Angry"],"Jovial = full of good humor = cheerful."),
("vocab",2,"Choose the synonym of LETHARGIC:","Sluggish",["Energetic","Active","Lively"],"Lethargic = lacking energy = sluggish."),
("vocab",1,"Choose the synonym of MERGE:","Combine",["Separate","Divide","Split"],"Merge = to combine or blend together."),
("vocab",2,"Choose the synonym of NOTORIOUS:","Infamous",["Famous positively","Unknown","Respected"],"Notorious = famous for something bad = infamous."),
("vocab",1,"Choose the synonym of OBSTINATE:","Stubborn",["Flexible","Agreeable","Yielding"],"Obstinate = refusing to change one's mind = stubborn."),
("vocab",2,"Choose the synonym of PERPETUAL:","Everlasting",["Temporary","Brief","Occasional"],"Perpetual = continuing forever = everlasting."),
("vocab",1,"Choose the synonym of QUAINT:","Charming (old-fashioned)",["Modern","Ordinary","Ugly"],"Quaint = attractively unusual, especially in an old-fashioned way."),
("vocab",2,"Choose the synonym of RETICENT:","Reserved",["Talkative","Outspoken","Loud"],"Reticent = not revealing thoughts/feelings readily = reserved."),
("vocab",1,"Choose the synonym of SINCERE:","Genuine",["Fake","Dishonest","Deceitful"],"Sincere = free from pretense; honest."),
("vocab",2,"Choose the synonym of TEDIOUS:","Boring",["Exciting","Interesting","Thrilling"],"Tedious = too long, slow, or dull = boring."),
("vocab",1,"Choose the synonym of URGENT:","Pressing",["Relaxed","Casual","Unimportant"],"Urgent = requiring immediate action = pressing."),
("vocab",2,"Choose the synonym of VIGILANT:","Watchful",["Careless","Negligent","Sleepy"],"Vigilant = keeping careful watch = watchful — a key trait for a Sub-Inspector."),
("vocab",1,"Choose the synonym of WEALTHY:","Affluent",["Poor","Needy","Broke"],"Wealthy = having great wealth = affluent."),
("vocab",2,"Choose the synonym of ZEALOUS:","Enthusiastic",["Indifferent","Apathetic","Bored"],"Zealous = filled with zeal/enthusiasm."),
("vocab",1,"Choose the synonym of ANCIENT:","Age-old",["Modern","Recent","New"],"Ancient = belonging to the very distant past."),
("vocab",2,"Choose the synonym of BLEAK:","Gloomy",["Bright","Cheerful","Sunny"],"Bleak = lacking hope or cheer = gloomy."),
("vocab",1,"Choose the synonym of COURAGEOUS:","Brave",["Cowardly","Timid","Fearful"],"Courageous = able to face danger = brave."),
("vocab",2,"Choose the synonym of DECEIVE:","Mislead",["Inform","Enlighten","Assist"],"Deceive = to cause someone to believe something false = mislead."),
("vocab",1,"Choose the synonym of EAGER:","Keen",["Reluctant","Unwilling","Indifferent"],"Eager = keenly wanting to do something."),
("vocab",2,"Choose the synonym of FACILITATE:","Ease",["Hinder","Block","Obstruct"],"Facilitate = to make an action easier."),
("vocab",1,"Choose the synonym of GRIEF:","Sorrow",["Joy","Happiness","Delight"],"Grief = deep sorrow, especially caused by loss."),
("vocab",2,"Choose the synonym of HAMPER:","Hinder",["Assist","Help","Support"],"Hamper = to hinder or impede progress."),
("vocab",1,"Choose the synonym of IDLE:","Inactive",["Busy","Active","Working"],"Idle = not working or being active."),
("vocab",2,"Choose the synonym of JEOPARDIZE:","Endanger",["Protect","Secure","Safeguard"],"Jeopardize = to put at risk = endanger."),
("vocab",1,"Choose the synonym of KIND:","Gentle",["Cruel","Harsh","Rude"],"Kind = having a gentle, considerate nature."),
("vocab",2,"Choose the synonym of LAVISH:","Extravagant",["Frugal","Sparse","Meager"],"Lavish = spending or providing in generous, extravagant amounts."),
("vocab",1,"Choose the synonym of MEEK:","Humble",["Arrogant","Proud","Bold"],"Meek = quiet, gentle, and submissive = humble."),
("vocab",2,"Choose the synonym of NEGLECT:","Disregard",["Attend to","Care for","Nurture"],"Neglect = failure to care for something = disregard."),
("vocab",1,"Choose the synonym of OMINOUS:","Threatening",["Promising","Cheerful","Reassuring"],"Ominous = giving an impression of danger = threatening."),
("vocab",2,"Choose the synonym of PONDER:","Reflect",["Ignore","Dismiss","Overlook"],"Ponder = to think carefully about something = reflect."),
("vocab",1,"Choose the synonym of QUELL:","Suppress",["Encourage","Provoke","Incite"],"Quell = to put an end to, typically by force = suppress — relevant to law and order duties."),
("vocab",2,"Choose the synonym of RAMPANT:","Widespread",["Rare","Controlled","Limited"],"Rampant = flourishing or spreading unchecked = widespread."),
("vocab",1,"Choose the synonym of SCARCE:","Rare",["Abundant","Plentiful","Common"],"Scarce = insufficient for demand = rare."),
("vocab",2,"Choose the synonym of TENACIOUS:","Persistent",["Weak-willed","Yielding","Quitting"],"Tenacious = holding firmly, not giving up = persistent."),
("vocab",1,"Choose the synonym of UNRULY:","Disorderly",["Obedient","Disciplined","Calm"],"Unruly = disorderly and disruptive — often used for crowds during police duty."),
("vocab",2,"Choose the synonym of VERIFY:","Confirm",["Doubt","Question","Dismiss"],"Verify = to make sure something is true = confirm."),
("vocab",1,"Choose the synonym of WITHER:","Shrivel",["Bloom","Flourish","Grow"],"Wither = to shrink and become dry, typically from loss of moisture."),
("vocab",2,"Choose the synonym of YIELD:","Surrender",["Resist","Defy","Fight"],"Yield = to give way or surrender."),
("vocab",1,"Choose the synonym of ZENITH:","Peak",["Bottom","Nadir","Base"],"Zenith = the highest point = peak."),
("vocab",2,"Choose the synonym of ABATE:","Diminish",["Increase","Intensify","Grow"],"Abate = to become less intense = diminish."),
("vocab",1,"Choose the synonym of BOLSTER:","Strengthen",["Weaken","Undermine","Damage"],"Bolster = to support or strengthen."),
("vocab",2,"Choose the synonym of CULPABLE:","Blameworthy",["Innocent","Guiltless","Blameless"],"Culpable = deserving blame — used in legal/criminal contexts."),
("vocab",1,"Choose the synonym of DILEMMA:","Predicament",["Solution","Certainty","Answer"],"Dilemma = a difficult situation requiring a choice = predicament."),
("vocab",2,"Choose the synonym of EVASIVE:","Elusive",["Direct","Straightforward","Honest"],"Evasive = tending to avoid commitment or directness = elusive."),

# ---------------- ANTONYMS ----------------
("vocab",2,"Choose the antonym of JEOPARDY:","Safety",["Danger","Risk","Peril"],"Jeopardy = danger; its opposite is safety."),
("vocab",1,"Choose the antonym of GENEROUS:","Stingy",["Kind","Charitable","Giving"],"Generous means giving freely; stingy is its opposite."),
("vocab",2,"Choose the antonym of ABUNDANT:","Scarce",["Plentiful","Ample","Sufficient"],"Abundant (plentiful) is opposite to scarce (insufficient)."),
("vocab",1,"Choose the antonym of BRAVE:","Cowardly",["Bold","Fearless","Daring"],"Brave means courageous; its opposite is cowardly."),
("vocab",2,"Choose the antonym of CONCEAL:","Reveal",["Hide","Cover","Mask"],"Conceal means to hide; reveal means to expose/show."),
("vocab",1,"Choose the antonym of DILIGENT:","Lazy",["Hardworking","Industrious","Sincere"],"Diligent (hardworking) is opposite to lazy."),
("vocab",2,"Choose the antonym of ELATED:","Depressed",["Joyful","Thrilled","Excited"],"Elated (very happy) is opposite to depressed."),
("vocab",1,"Choose the antonym of FRIEND:","Foe",["Ally","Companion","Buddy"],"Friend is opposite to foe (enemy)."),
("vocab",2,"Choose the antonym of GENUINE:","Fake",["Authentic","Real","True"],"Genuine (real) is opposite to fake (counterfeit)."),
("vocab",1,"Choose the antonym of HONEST:","Deceitful",["Truthful","Sincere","Frank"],"Honest is opposite to deceitful."),
("vocab",2,"Choose the antonym of INCLUDE:","Exclude",["Add","Incorporate","Involve"],"Include (to add in) is opposite to exclude (to leave out)."),
("vocab",1,"Choose the antonym of JOY:","Sorrow",["Happiness","Delight","Pleasure"],"Joy is opposite to sorrow (grief)."),
("vocab",2,"Choose the antonym of KIND:","Cruel",["Gentle","Compassionate","Caring"],"Kind is opposite to cruel."),
("vocab",1,"Choose the antonym of LOYAL:","Disloyal",["Faithful","Devoted","True"],"Loyal is opposite to disloyal (unfaithful)."),
("vocab",2,"Choose the antonym of MAJOR:","Minor",["Significant","Important","Chief"],"Major (great) is opposite to minor (small)."),
("vocab",1,"Choose the antonym of NOISY:","Quiet",["Loud","Deafening","Blaring"],"Noisy is opposite to quiet (silent)."),
("vocab",2,"Choose the antonym of OBEDIENT:","Defiant",["Compliant","Submissive","Dutiful"],"Obedient is opposite to defiant (rebellious)."),
("vocab",1,"Choose the antonym of PERMANENT:","Temporary",["Lasting","Enduring","Fixed"],"Permanent (lasting forever) is opposite to temporary."),
("vocab",2,"Choose the antonym of QUALIFIED:","Unqualified",["Skilled","Competent","Trained"],"Qualified is opposite to unqualified (lacking necessary skills)."),
("vocab",1,"Choose the antonym of RIGID:","Flexible",["Stiff","Firm","Inflexible"],"Rigid (stiff) is opposite to flexible."),
("vocab",2,"Choose the antonym of SUPERIOR:","Inferior",["Better","Higher","Excellent"],"Superior is opposite to inferior (lower in rank/quality)."),
("vocab",1,"Choose the antonym of TRANSPARENT:","Opaque",["Clear","Visible","See-through"],"Transparent (clear) is opposite to opaque (not letting light through)."),
("vocab",2,"Choose the antonym of UNITE:","Divide",["Combine","Merge","Join"],"Unite is opposite to divide (separate)."),
("vocab",1,"Choose the antonym of VICTORY:","Defeat",["Triumph","Win","Success"],"Victory is opposite to defeat (loss)."),
("vocab",2,"Choose the antonym of WISE:","Foolish",["Intelligent","Sensible","Prudent"],"Wise is opposite to foolish."),
("vocab",1,"Choose the antonym of EXPAND:","Contract",["Enlarge","Grow","Extend"],"Expand (grow bigger) is opposite to contract (shrink)."),
("vocab",2,"Choose the antonym of FLEXIBLE:","Rigid",["Adaptable","Adjustable","Pliable"],"Flexible is opposite to rigid (stiff, unbending)."),
("vocab",1,"Choose the antonym of GUILTY:","Innocent",["Culpable","Blameworthy","At fault"],"Guilty is opposite to innocent (not guilty)."),
("vocab",2,"Choose the antonym of HUMBLE:","Arrogant",["Modest","Meek","Unassuming"],"Humble is opposite to arrogant (proud)."),
("vocab",1,"Choose the antonym of INCREASE:","Decrease",["Rise","Grow","Expand"],"Increase is opposite to decrease (reduce)."),
("vocab",2,"Choose the antonym of JUSTICE:","Injustice",["Fairness","Equity","Righteousness"],"Justice is opposite to injustice (unfairness)."),
("vocab",1,"Choose the antonym of KNOWLEDGE:","Ignorance",["Wisdom","Awareness","Understanding"],"Knowledge is opposite to ignorance."),
("vocab",2,"Choose the antonym of LIBERAL:","Conservative",["Open-minded","Progressive","Tolerant"],"Liberal is opposite to conservative (traditional, cautious of change)."),
("vocab",1,"Choose the antonym of MODERN:","Ancient",["Contemporary","Current","Recent"],"Modern is opposite to ancient (very old)."),
("vocab",2,"Choose the antonym of NEGLIGENT:","Careful",["Careless","Sloppy","Reckless"],"Negligent (careless) is opposite to careful — critical for duty conduct."),
("vocab",1,"Choose the antonym of OPTIMISTIC:","Pessimistic",["Hopeful","Positive","Confident"],"Optimistic is opposite to pessimistic (expecting the worst)."),
("vocab",2,"Choose the antonym of PROHIBIT:","Permit",["Ban","Forbid","Restrict"],"Prohibit (to forbid) is opposite to permit (to allow)."),
("vocab",1,"Choose the antonym of DISPARITY:","Similarity",["Difference","Gap","Inequality"],"Disparity (difference) is opposite to similarity."),
("vocab",2,"Choose the antonym of RELUCTANT:","Willing",["Hesitant","Unwilling","Resistant"],"Reluctant is opposite to willing (eager to do something)."),
("vocab",1,"Choose the antonym of SOLID:","Liquid",["Firm","Hard","Dense"],"Solid is opposite to liquid (as states of matter) — or 'hollow' in a structural sense."),
("vocab",2,"Choose the antonym of TRANQUIL:","Turbulent",["Calm","Peaceful","Serene"],"Tranquil (calm) is opposite to turbulent (chaotic)."),
("vocab",1,"Choose the antonym of URBAN:","Rural",["City-based","Metropolitan","Civic"],"Urban (city) is opposite to rural (countryside)."),
("vocab",2,"Choose the antonym of VALID:","Invalid",["Legitimate","Legal","Authentic"],"Valid is opposite to invalid (not legally acceptable)."),
("vocab",1,"Choose the antonym of WISE:","Unwise",["Prudent","Sensible","Judicious"],"Wise is opposite to unwise (foolish)."),

# ---------------- SPELLING ----------------
("spelling",1,"Choose the correctly spelt word:","Accommodate",["Acommodate","Accomodate","Acomodate"],"Accommodate has double 'c' and double 'm' — a commonly misspelled word."),
("spelling",1,"Choose the correctly spelt word:","Necessary",["Neccessary","Necesary","Neccesary"],"Necessary has one 'c' and two 's'."),
("spelling",1,"Choose the correctly spelt word:","Occurrence",["Occurence","Ocurrence","Occurrance"],"Occurrence doubles both 'r' and has 'ence' at the end."),
("spelling",2,"Choose the correctly spelt word:","Embarrass",["Embarass","Embarras","Embaras"],"Embarrass has double 'r' and double 's'."),
("spelling",1,"Choose the correctly spelt word:","Definitely",["Definately","Definitly","Definetely"],"Definitely is often misspelled as 'definately' — remember it has 'finite' inside."),
("spelling",1,"Choose the correctly spelt word:","Separate",["Seperate","Separete","Seperete"],"Separate has 'a' in the middle, not 'e' — think 'a rat' in separate."),
("spelling",2,"Choose the correctly spelt word:","Rhythm",["Rythm","Rhythem","Rythem"],"Rhythm is famously vowel-less except the 'y' — commonly misspelled."),
("spelling",1,"Choose the correctly spelt word:","Occasion",["Ocassion","Occassion","Ocasion"],"Occasion has double 'c' and one 's'."),
("spelling",1,"Choose the correctly spelt word:","Believe",["Beleive","Belive","Beleve"],"'i before e except after c' — believe follows the rule."),
("spelling",2,"Choose the correctly spelt word:","Millennium",["Milennium","Millenium","Milenium"],"Millennium has double 'l' and double 'n'."),
("spelling",1,"Choose the correctly spelt word:","Government",["Goverment","Governement","Govermment"],"Government keeps the 'n' before 'ment' — commonly dropped in error."),
("spelling",2,"Choose the correctly spelt word:","Committee",["Comittee","Commitee","Committe"],"Committee doubles 'm', 't', and ends in double 'e'."),
("spelling",1,"Choose the correctly spelt word:","Privilege",["Privilage","Priviledge","Previlege"],"Privilege has no 'd' — a common error is adding one."),
("spelling",2,"Choose the correctly spelt word:","Maintenance",["Maintainance","Maintenence","Maintainence"],"Maintenance keeps 'ten' not 'tain' in its middle."),
("spelling",1,"Choose the correctly spelt word:","Recommend",["Recomend","Reccommend","Recommand"],"Recommend has double 'm' and one 'c'."),
("spelling",2,"Choose the correctly spelt word:","Questionnaire",["Questionaire","Questionnnaire","Questionair"],"Questionnaire doubles the 'n' — French-origin spelling."),
("spelling",1,"Choose the correctly spelt word:","Tomorrow",["Tommorow","Tomorow","Tommorrow"],"Tomorrow has one 'm' and double 'r'."),
("spelling",2,"Choose the correctly spelt word:","Bureaucracy",["Beaurocracy","Buraucracy","Bureacracy"],"Bureaucracy retains the French 'eau' spelling — tricky word."),
("spelling",1,"Choose the correctly spelt word:","Neighbour",["Nieghbour","Neighbuor","Naighbour"],"Neighbour follows 'ei' after 'gh' — 'i before e except after c' has this exception."),
("spelling",2,"Choose the correctly spelt word:","Conscience",["Consience","Concience","Conscence"],"Conscience has 'sc' in the middle — often confused with 'conscious'."),
("spelling",1,"Choose the correctly spelt word:","Pursue",["Persue","Pursu","Persu"],"Pursue starts with 'pur', not 'per'."),
("spelling",2,"Choose the correctly spelt word:","Liaison",["Liason","Liaision","Laison"],"Liaison keeps both 'i's — a French loanword, often misspelled."),
("spelling",1,"Choose the correctly spelt word:","Guarantee",["Garantee","Guarentee","Gaurantee"],"Guarantee starts 'gua' and ends 'antee'."),
("spelling",2,"Choose the correctly spelt word:","Entrepreneur",["Entreprenuer","Entreprenur","Enterpreneur"],"Entrepreneur keeps the French 'eur' ending — commonly misspelled."),
("spelling",1,"Choose the correctly spelt word:","February",["Feburary","Febuary","Februrary"],"February retains the first 'r' after 'Feb', often dropped in speech and writing."),
("spelling",2,"Choose the correctly spelt word:","Handkerchief",["Hankerchief","Handkerchef","Handkercheif"],"Handkerchief has 'chief' at the end, following the ie-before-f pattern of 'chief'."),
("spelling",1,"Choose the correctly spelt word:","Independent",["Independant","Independdent","Indipendent"],"Independent ends in '-ent', not '-ant'."),
("spelling",2,"Choose the correctly spelt word:","Accessible",["Accessable","Acessible","Assessible"],"Accessible ends in '-ible', and starts with double 'c'."),
("spelling",1,"Choose the correctly spelt word:","Beginning",["Begining","Beginnning","Begginning"],"Beginning doubles the 'n' before '-ing'."),
("spelling",2,"Choose the correctly spelt word:","Persistent",["Persistant","Persistint","Persistient"],"Persistent ends in '-ent', following the pattern like 'consistent'."),

# ---------------- IDIOMS / ONE-WORD SUBSTITUTION ----------------
("idioms",1,"'To break the ice' means:","To start a conversation in a stiff situation",["To end a friendship","To cause a delay","To break something literally"],"Breaking the ice means easing tension or starting conversation."),
("idioms",1,"One who engages in an art or activity for pleasure rather than payment is called:","Amateur",["Professional","Connoisseur","Novice"],"Amateur = does it for love, not money."),
("idioms",2,"'A blessing in disguise' means:","Something good that initially seemed bad",["A curse in hidden form","An obvious advantage","A surprise gift"],"It describes a misfortune that turns out beneficial later."),
("idioms",1,"A person who knows everything is called:","Know-it-all / Omniscient",["Illiterate","Novice","Amateur"],"Omniscient formally means 'all-knowing'; know-it-all is the common idiom."),
("idioms",2,"'To beat around the bush' means:","To avoid the main topic",["To attack directly","To finish quickly","To hide in a garden"],"It means speaking evasively instead of directly."),
("idioms",1,"One who cannot read or write is called:","Illiterate",["Amateur","Literate","Erudite"],"Illiterate = unable to read or write."),
("idioms",2,"'To let the cat out of the bag' means:","To reveal a secret accidentally",["To adopt a pet","To finish a task","To trap someone"],"The idiom describes an unintentional disclosure."),
("idioms",1,"A place where birds are kept is called:","Aviary",["Apiary","Aquarium","Sanctuary"],"Aviary = enclosure for birds; apiary = for bees."),
("idioms",1,"A place where bees are kept is called:","Apiary",["Aviary","Beehive garden","Sanctuary"],"Apiary = a place where bees/honey are kept commercially."),
("idioms",2,"'To add fuel to the fire' means:","To make a bad situation worse",["To help solve a problem","To calm a situation","To ignore an issue"],"It means aggravating an already tense situation."),
("idioms",1,"One who loves books is called:","Bibliophile",["Bibliophobe","Cynophile","Xenophile"],"Bibliophile = a lover of books."),
("idioms",2,"'To hit the nail on the head' means:","To describe something exactly right",["To fail completely","To hurt someone","To finish work quickly"],"The idiom means to be precisely accurate."),
("idioms",1,"A person who is 50 years old is described using which word for the anniversary period?","Golden Jubilee",["Silver Jubilee","Platinum Jubilee","Diamond Jubilee"],"Golden Jubilee = 50 years; Silver = 25 years; Diamond = 60 or 75 years."),
("idioms",1,"A doctor who treats children is called a:","Paediatrician",["Gynaecologist","Orthopaedist","Dermatologist"],"Paediatrician specializes in children's health."),
("idioms",2,"'To turn over a new leaf' means:","To start behaving in a better way",["To read a new book","To change one's job","To move to a new house"],"It means reforming and starting afresh."),
("idioms",1,"A person who studies the stars and planets is called:","Astronomer",["Astrologer","Geologist","Meteorologist"],"Astronomer studies celestial bodies scientifically; astrologer studies horoscopes."),
("idioms",2,"'Once in a blue moon' means:","Very rarely",["Very frequently","Every night","Regularly"],"The idiom refers to a rare occurrence."),
("idioms",1,"A person who is indifferent to pleasure or pain is called:","Stoic",["Cynic","Epicurean","Hedonist"],"Stoic = one who endures hardship without complaint."),
("idioms",2,"'To cost an arm and a leg' means:","To be very expensive",["To be free of cost","To be moderately priced","To require physical labour"],"The idiom describes something very costly."),
("idioms",1,"A government by the rich is called:","Plutocracy",["Democracy","Autocracy","Theocracy"],"Plutocracy = rule by the wealthy."),
("idioms",2,"A government by one ruler with absolute power is called:","Autocracy",["Democracy","Plutocracy","Bureaucracy"],"Autocracy = rule by a single person with unlimited authority."),
("idioms",1,"'To keep one's fingers crossed' means:","To hope for good luck",["To be angry","To refuse something","To promise firmly"],"The idiom expresses hope for a favourable outcome."),
("idioms",2,"A person who speaks many languages is called:","Polyglot",["Linguist only","Bilingual only","Translator"],"Polyglot = a person who knows and can use several languages."),
("idioms",1,"'Actions speak louder than words' means:","What you do matters more than what you say",["Loud people are always right","Silence is more effective than speech","Words are more powerful than deeds"],"The idiom emphasizes that deeds carry more weight than promises."),
("idioms",2,"A person who eats human flesh is called:","Cannibal",["Carnivore","Vegetarian","Omnivore"],"Cannibal specifically refers to eating one's own species (humans)."),
("idioms",1,"'To burn the midnight oil' means:","To work late into the night",["To waste resources","To relax at night","To cook food at night"],"The idiom refers to working or studying very late."),
("idioms",2,"One who is unable to pay one's debts is called:","Insolvent",["Solvent","Wealthy","Affluent"],"Insolvent = unable to pay debts owed; the opposite is solvent."),
("idioms",1,"'To spill the beans' means:","To reveal secret information",["To cook a meal","To waste food","To argue loudly"],"It's synonymous with 'letting the cat out of the bag' — revealing a secret."),
("idioms",2,"A word that reads the same forwards and backwards is called a:","Palindrome",["Acronym","Anagram","Homonym"],"E.g., 'madam', 'level' — palindromes read identically both ways."),
("idioms",1,"'Bite the bullet' means:","To face a difficult situation bravely",["To eat quickly","To avoid a challenge","To argue fiercely"],"The idiom means enduring something unpleasant with courage."),
("idioms",2,"One who works for free is called a:","Volunteer",["Employee","Mercenary","Contractor"],"Volunteer = a person who offers services without payment."),
]
