# ga_facts_3.py — Science (55) + Sports (55) + People in News (45) + Current Affairs 2025-26 (60)
FACTS = [
# ---------------- SCIENCE & RESEARCH ----------------
("science",1,"The unit of electric current is:","Ampere",["Volt","Ohm","Watt"],"Current is measured in amperes (A); voltage in volts, resistance in ohms."),
("science",1,"Water boils at what temperature at sea level (Celsius)?","100°C",["90°C","80°C","120°C"],"At standard atmospheric pressure, water boils at 100°C / 212°F."),
("science",1,"The chemical symbol for Sodium is:","Na",["So","Sd","S"],"From Latin 'Natrium'; K is potassium, Fe is iron."),
("science",2,"The powerhouse of the cell is the:","Mitochondria",["Nucleus","Ribosome","Golgi body"],"Mitochondria generate ATP through cellular respiration."),
("science",1,"Which gas do plants absorb during photosynthesis?","Carbon dioxide",["Oxygen","Nitrogen","Hydrogen"],"Plants take in CO₂ and release O₂ using sunlight energy."),
("science",1,"The SI unit of force is:","Newton",["Joule","Pascal","Watt"],"Force = mass × acceleration, measured in newtons (N)."),
("science",2,"Which vitamin is produced by the human body when exposed to sunlight?","Vitamin D",["Vitamin C","Vitamin A","Vitamin K"],"UV rays trigger vitamin D synthesis in the skin."),
("science",1,"The study of heavenly bodies is called:","Astronomy",["Astrology","Geology","Seismology"],"Astronomy is scientific study of stars, planets, galaxies."),
("science",2,"The blood group known as the 'universal donor' is:","O negative",["AB positive","A positive","B negative"],"O-negative red cells lack A, B, and Rh antigens, so most bodies accept them."),
("science",2,"The 'universal recipient' blood group is:","AB positive",["O negative","B positive","A negative"],"AB-positive plasma/cells accept from all other groups."),
("science",1,"The normal human body temperature is approximately:","37°C (98.6°F)",["35°C","40°C","39°C"],"Average core body temperature is about 37°C."),
("science",2,"DNA stands for:","Deoxyribonucleic acid",["Dioxyribose nucleic acid","Di-nucleic acid","Deoxyribose nitrogen acid"],"DNA carries the genetic code in a double-helix structure (Watson–Crick)."),
("science",1,"The hardest natural substance on Earth is:","Diamond",["Gold","Iron","Quartz"],"Diamond, a crystal form of carbon, tops the Mohs hardness scale."),
("science",2,"Which organ in the human body produces insulin?","Pancreas",["Liver","Kidney","Spleen"],"Beta cells in the pancreatic islets secrete insulin to regulate blood sugar."),
("science",1,"Which planet is known as the 'Morning Star' / 'Evening Star'?","Venus",["Mercury","Mars","Jupiter"],"Venus is the brightest planet visible near sunrise/sunset."),
("science",2,"The speed of light in vacuum is approximately:","3 × 10⁸ m/s",["3 × 10⁶ m/s","3 × 10¹⁰ m/s","3 × 10⁵ m/s"],"Light travels at about 299,792 km/s in a vacuum."),
("science",1,"Which of these is a greenhouse gas primarily responsible for global warming?","Carbon dioxide",["Nitrogen","Oxygen","Argon"],"CO₂, methane and water vapour trap heat in the atmosphere."),
("science",2,"The layer of the atmosphere that protects Earth from harmful UV rays is:","Ozone layer (stratosphere)",["Troposphere","Ionosphere","Mesosphere"],"Ozone (O₃) in the stratosphere absorbs most UV-B and UV-C radiation."),
("science",1,"Which scientist proposed the theory of relativity?","Albert Einstein",["Isaac Newton","Galileo Galilei","Niels Bohr"],"Einstein's special (1905) and general (1915) relativity reshaped physics."),
("science",1,"Sir Isaac Newton is best known for the law of:","Gravitation",["Relativity","Evolution","Genetics"],"Newton's law of universal gravitation and his three laws of motion."),
("science",2,"The vaccine for polio was developed by:","Jonas Salk",["Edward Jenner","Louis Pasteur","Alexander Fleming"],"Salk's inactivated polio vaccine (1955) was a landmark in public health."),
("science",1,"Penicillin, the first antibiotic, was discovered by:","Alexander Fleming",["Robert Koch","Louis Pasteur","Jonas Salk"],"Fleming discovered it accidentally from Penicillium mould in 1928."),
("science",2,"ISRO's Chandrayaan-3 successfully landed near the Moon's south pole in:","2023",["2019","2021","2024"],"Vikram lander touched down on 23 August 2023, marking India as the first nation there."),
("science",2,"Chandrayaan-3's landing site was later named:","Shiv Shakti Point",["Tiranga Point","Vikram Point","Bharat Point"],"PM Modi named the landing spot 'Shiv Shakti Point' in 2023."),
("science",1,"ISRO stands for:","Indian Space Research Organisation",["Indian Satellite Research Office","International Space Research Org","Indian Science Research Org"],"Headquartered in Bengaluru, founded 1969."),
("science",2,"India's first satellite, launched in 1975, was named:","Aryabhata",["Bhaskara","Rohini","INSAT-1"],"Named after the ancient mathematician-astronomer, launched via a Soviet rocket."),
("science",2,"Gaganyaan is India's mission for:","Human spaceflight",["Mars exploration","Moon mining","Weather satellites"],"ISRO's Gaganyaan aims to send Indian astronauts to low Earth orbit."),
("science",1,"The gas used in balloons that makes them float is usually:","Helium",["Oxygen","Nitrogen","Carbon dioxide"],"Helium is lighter than air and non-flammable, unlike hydrogen."),
("science",2,"pH value of a neutral solution (like pure water) is:","7",["0","14","10"],"pH below 7 is acidic, above 7 is basic/alkaline."),
("science",1,"Which part of the plant conducts photosynthesis mainly?","Leaves",["Roots","Stem","Flowers"],"Chlorophyll in leaf cells captures sunlight for photosynthesis."),
("science",2,"The process by which plants lose water vapour through leaves is:","Transpiration",["Respiration","Photosynthesis","Osmosis"],"Water evaporates through stomata, aiding nutrient transport."),
("science",1,"Which organ pumps blood throughout the human body?","Heart",["Liver","Lungs","Kidney"],"The four-chambered heart circulates blood via the circulatory system."),
("science",2,"The number of chromosomes in a normal human cell is:","46",["44","48","23"],"23 pairs = 46 chromosomes; gametes carry 23 (half)."),
("science",1,"Sound cannot travel through:","Vacuum",["Water","Air","Solids"],"Sound needs a medium; it cannot propagate in a vacuum (unlike light)."),
("science",2,"The instrument used to measure atmospheric pressure is:","Barometer",["Thermometer","Hygrometer","Anemometer"],"Barometers measure air pressure; anemometers measure wind speed."),
("science",1,"Which of the following is NOT a renewable energy source?","Coal",["Solar","Wind","Hydro"],"Coal is a fossil fuel and non-renewable."),
("science",2,"The 'Green Revolution' primarily boosted production of:","Wheat and rice",["Cotton","Tea","Sugarcane"],"HYV seeds, irrigation and fertilizers raised foodgrain output from the 1960s."),
("science",2,"Which Indian scientist led India's nuclear programme and the 1974 Pokhran test era?","Homi J. Bhabha (founding) / Raja Ramanna (1974 test)",["Vikram Sarabhai","C.V. Raman","APJ Abdul Kalam"],"Bhabha founded India's atomic energy programme; Ramanna led the 1974 Pokhran-I test."),
("science",1,"APJ Abdul Kalam, India's 'Missile Man', later became:","President of India",["Prime Minister","ISRO Chairman only","Chief Justice"],"Kalam served as the 11th President (2002–2007) after his DRDO/ISRO career."),
("science",2,"C.V. Raman won the Nobel Prize in Physics for discovering:","The Raman Effect (light scattering)",["The transistor","Radioactivity","X-rays"],"He won in 1930, India's first Nobel in science."),
("science",1,"The blood vessels that carry blood away from the heart are:","Arteries",["Veins","Capillaries","Nerves"],"Arteries carry oxygenated blood away (except pulmonary artery); veins return it."),
("science",2,"Which of these diseases is caused by a virus?","Influenza",["Malaria","Tuberculosis","Cholera"],"Flu is viral; malaria is parasitic, TB and cholera are bacterial."),
("science",1,"Malaria is spread by which insect?","Female Anopheles mosquito",["Housefly","Aedes mosquito (dengue)","Tsetse fly"],"Anopheles spreads the Plasmodium parasite; Aedes spreads dengue/Zika."),
("science",2,"Dengue and Chikungunya are spread mainly by:","Aedes mosquito",["Anopheles mosquito","Culex mosquito","Sandfly"],"The day-biting Aedes aegypti is the primary vector."),
("science",1,"The largest organ of the human body is the:","Skin",["Liver","Lungs","Brain"],"Skin covers roughly 2 m² and forms the body's largest organ by area/mass."),
("science",2,"Which technology is used in GPS to determine location?","Satellite triangulation/trilateration",["Radar only","Sonar","Wi-Fi signals"],"GPS receivers calculate position from signals of multiple orbiting satellites."),
("science",1,"5G refers to:","The fifth generation of mobile network technology",["A type of processor","A satellite band","A battery standard"],"5G offers higher speed and lower latency than 4G LTE."),
("science",2,"Artificial Intelligence chatbots like ChatGPT are built on which type of model?","Large Language Models (LLMs)",["Simple databases","Spreadsheets","Static websites"],"LLMs are trained on huge text corpora using deep neural networks (transformers)."),
("science",2,"India's indigenous aircraft carrier, commissioned in 2022, is named:","INS Vikrant",["INS Vikramaditya","INS Viraat","INS Chakra"],"INS Vikrant, built at Kochi, is India's first indigenous carrier."),
("science",2,"Agni-V, tested by India, is a type of:","Intercontinental ballistic missile",["Fighter jet","Submarine","Satellite launcher"],"Agni-V has a range of over 5,000 km, developed by DRDO."),
("science",1,"BrahMos is a joint venture missile between India and:","Russia",["France","USA","Israel"],"BrahMos (Brahmaputra + Moskva) is a supersonic cruise missile."),
("science",2,"Aditya-L1, ISRO's mission to study the Sun, was launched in:","2023",["2021","2024","2019"],"Aditya-L1 reached the Sun-Earth L1 point to observe solar activity."),
("science",2,"India's Mars Orbiter Mission (Mangalyaan) made India the first country to:","Reach Mars orbit on its maiden attempt",["Land a rover on Mars","Build a Mars colony","Photograph Mars' moons closely"],"Launched 2013, it succeeded in 2014 at a fraction of other nations' costs."),
("science",1,"Antibiotics are effective against:","Bacteria",["Viruses","Vitamin deficiency","Genetic disorders"],"Antibiotics don't work on viral infections like flu or COVID-19."),
("science",2,"CRISPR technology is primarily used for:","Gene editing",["Weather forecasting","Data encryption","Satellite imaging"],"CRISPR-Cas9 lets scientists precisely edit DNA sequences."),
("science",1,"Photosynthesis in plants requires sunlight, water and:","Carbon dioxide",["Oxygen","Nitrogen","Methane"],"6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂."),

# ---------------- SPORTS ----------------
("sports",1,"India won the ICC Men's T20 World Cup 2024 by defeating:","South Africa",["Australia","England","New Zealand"],"India beat South Africa in the final at Barbados to win its second T20 title."),
("sports",2,"India won the ICC Champions Trophy 2025 held in:","Dubai (hybrid model, Pakistan hosting)",["Pakistan","India","England"],"Due to security concerns, India played all its matches at neutral venue Dubai under a hybrid model."),
("sports",1,"Who captained the Indian cricket team to the 2024 T20 World Cup title?","Rohit Sharma",["Virat Kohli","Hardik Pandya","KL Rahul"],"Rohit Sharma led India to the trophy and retired from T20Is right after."),
("sports",2,"Neeraj Chopra won India's first-ever Olympic gold in athletics at which Games?","Tokyo 2020 (held in 2021)",["Paris 2024","Rio 2016","London 2012"],"Neeraj won javelin gold at Tokyo with an 87.58 m throw; he took silver at Paris 2024."),
("sports",2,"At the Paris 2024 Olympics, India's javelin thrower Neeraj Chopra won:","Silver medal",["Gold medal","Bronze medal","No medal"],"Neeraj finished second behind Pakistan's Arshad Nadeem at Paris 2024."),
("sports",2,"Arshad Nadeem, who beat Neeraj Chopra at Paris 2024, represents:","Pakistan",["Bangladesh","Sri Lanka","Afghanistan"],"Nadeem set an Olympic javelin record (92.97 m) to win gold."),
("sports",1,"India's first individual Olympic gold medallist was:","Abhinav Bindra (2008, shooting)",["Neeraj Chopra","Rajyavardhan Rathore","Leander Paes"],"Bindra won gold in 10m air rifle at Beijing 2008."),
("sports",2,"How many medals did India win at the Paris 2024 Olympics in total?","6",["7","5","4"],"India won 1 silver and 5 bronze medals at Paris 2024 (no gold)."),
("sports",1,"The 2023 Cricket World Cup (ODI) was hosted by:","India",["England","Australia","South Africa"],"India hosted the 2023 ODI World Cup; Australia won the final at Ahmedabad, beating India."),
("sports",2,"Who was the Player of the Tournament at the 2023 ODI Cricket World Cup?","Virat Kohli",["Rohit Sharma","Mohammed Shami","Travis Head"],"Kohli scored the most runs (765) including a record 50th ODI century."),
("sports",1,"The IPL 2024 title was won by:","Kolkata Knight Riders",["Sunrisers Hyderabad","Chennai Super Kings","Mumbai Indians"],"KKR beat SRH to win their third IPL title."),
("sports",2,"Who won the IPL 2025 title?","Royal Challengers Bengaluru",["Punjab Kings","Gujarat Titans","Mumbai Indians"],"RCB won their maiden IPL title in 2025, beating Punjab Kings in the final."),
("sports",1,"Which country won the FIFA World Cup 2022?","Argentina",["France","Brazil","Germany"],"Argentina beat France on penalties in Qatar; Messi lifted his first World Cup."),
("sports",2,"Lionel Messi plays club football (as of recent years) for:","Inter Miami CF",["Paris Saint-Germain","FC Barcelona","Manchester City"],"Messi moved to MLS side Inter Miami in 2023 after his PSG stint."),
("sports",1,"The 2024 Summer Olympics were held in:","Paris, France",["Tokyo, Japan","Los Angeles, USA","London, UK"],"Paris hosted the Games from 26 July to 11 August 2024."),
("sports",2,"The 2028 Summer Olympics are scheduled to be held in:","Los Angeles, USA",["Brisbane, Australia","Paris, France","Delhi, India"],"LA will host for a third time in 2028; Brisbane hosts in 2032."),
("sports",1,"Sachin Tendulkar, the 'Master Blaster', played international cricket for:","India",["Sri Lanka","England","Pakistan"],"Tendulkar holds the record for most international runs and centuries."),
("sports",2,"P.V. Sindhu, India's ace badminton player, has won Olympic medals in:","Rio 2016 (silver) and Tokyo 2020 (bronze)",["Only Rio 2016","Only Tokyo 2020","Paris 2024 gold"],"Sindhu is India's only individual to win 2 Olympic medals in singles events (badminton)."),
("sports",1,"Which Indian wrestler won gold medals at multiple Olympics/Asian levels and led protests in 2023 over sexual harassment allegations?","Vinesh Phogat",["Sakshi Malik","Geeta Phogat","Babita Phogat"],"Vinesh led the 2023 wrestlers' protest against the WFI chief; she also competed at Paris 2024."),
("sports",2,"Vinesh Phogat was disqualified from the Paris 2024 Olympic final due to:","Being marginally overweight before the final",["A doping violation","An injury","A rules technicality on grip"],"She missed the 50kg weight limit by 100g on the final's morning, causing disqualification and huge controversy."),
("sports",1,"Which sport is Mary Kom associated with?","Boxing",["Wrestling","Weightlifting","Badminton"],"Mary Kom, a 6-time World Champion, won bronze at London 2012 Olympics."),
("sports",2,"Which shooter, from Haryana, won two bronze medals at the Paris 2024 Olympics?","Manu Bhaker",["Saurabh Chaudhary","Rahi Sarnobat","Apurvi Chandela"],"Manu Bhaker became the first Indian to win 2 medals at a single Olympics (individual + mixed team, 10m air pistol)."),
("sports",1,"Which trophy is awarded to the winner of the Test cricket series between India and Australia?","Border-Gavaskar Trophy",["Ashes","Frank Worrell Trophy","Anthony de Mello Trophy"],"Named after Allan Border and Sunil Gavaskar."),
("sports",1,"The Ashes is a cricket Test series played between:","England and Australia",["India and England","Australia and South Africa","England and West Indies"],"One of cricket's oldest rivalries, dating to 1882."),
("sports",2,"The Ranji Trophy is India's premier tournament in which sport format?","Domestic first-class cricket",["Domestic T20 cricket","Domestic hockey","Domestic football"],"Named after Ranjitsinhji, contested by state/regional teams since 1934."),
("sports",1,"Hockey legend Major Dhyan Chand is associated with which sport?","Field hockey",["Football","Cricket","Athletics"],"Dhyan Chand led India to hockey Olympic golds in 1928, 1932, 1936; India's highest sports honour is named after him (Major Dhyan Chand Khel Ratna)."),
("sports",1,"India's highest sporting honour is called the:","Major Dhyan Chand Khel Ratna Award",["Arjuna Award","Padma Shri","Dronacharya Award"],"Renamed from Rajiv Gandhi Khel Ratna in 2021."),
("sports",2,"The Dronacharya Award is given for excellence in:","Coaching",["Playing","Sports journalism","Sports administration"],"It honours coaches who produce medal-winning athletes."),
("sports",1,"Cricket's shortest format played in international cricket is:","T20I",["ODI","Test","The Hundred"],"T20 International matches run 20 overs per side; The Hundred is a franchise format, not international."),
("sports",2,"Who holds the record for the most centuries in international cricket?","Sachin Tendulkar (100 centuries)",["Virat Kohli","Ricky Ponting","Kumar Sangakkara"],"Tendulkar's landmark 100th century remains cricket's most cited batting record."),
("sports",1,"Which Indian city hosted the 2010 Commonwealth Games?","New Delhi",["Mumbai","Chennai","Bengaluru"],"India's only Commonwealth Games hosting to date."),
("sports",2,"The Khelo India Youth Games promote:","Grassroots sporting talent in India",["Only Olympic-level athletes","International tournaments abroad","Corporate sports leagues"],"Launched 2018 to identify and nurture young sporting talent nationwide."),
("sports",1,"Which sport does Rohan Bopanna play, having won a Grand Slam doubles title in 2024?","Tennis",["Badminton","Table tennis","Squash"],"Bopanna won the Australian Open 2024 men's doubles title at age 43, the oldest to win a Slam doubles title."),
("sports",2,"Gukesh Dommaraju became the youngest ever World Chess Champion in:","2024",["2022","2023","2021"],"D. Gukesh, 18, beat Ding Liren to become the youngest undisputed world chess champion."),
("sports",1,"Viswanathan Anand, India's chess legend, is a ______ time World Champion.","Five",["Three","Seven","Two"],"Anand won the World Chess Championship five times (2000, 2007, 2008, 2010, 2012)."),
("sports",2,"India's men's hockey team won bronze at which recent Olympics?","Tokyo 2020 and Paris 2024 (back-to-back bronze)",["Only Tokyo 2020","Only Rio 2016","Only London 2012"],"India ended a 41-year medal drought at Tokyo 2020 and repeated bronze at Paris 2024."),
("sports",1,"Which stadium in Ahmedabad is the world's largest cricket stadium?","Narendra Modi Stadium",["Eden Gardens","Wankhede Stadium","M. Chinnaswamy Stadium"],"With a capacity of over 132,000, it's the largest cricket stadium globally."),
("sports",2,"The 2023 Asian Games were hosted by which Chinese city?","Hangzhou",["Beijing","Guangzhou","Shanghai"],"India won a record 107 medals at the 2023 Asian Games in Hangzhou."),
("sports",1,"Which award recognizes India's best sports coaches at the grassroots and international level combined with lifetime achievement?","Dronacharya Award (Lifetime category included)",["Arjuna Award","Khel Ratna","Padma Vibhushan"],"Dronacharya honours coaching excellence, including a lifetime achievement category."),
("sports",2,"Neeraj Chopra hails from which state?","Haryana",["Punjab","Uttar Pradesh","Rajasthan"],"Born in Khandra village, Panipat district, Haryana."),
("sports",1,"Which trophy is contested in the India–Pakistan cricket rivalry historically (bilateral Tests)?","No fixed trophy — bilateral series (rare since 2013)",["Border-Gavaskar Trophy","Asia Cup only","Ashes"],"India and Pakistan have not played bilateral series since 2012-13; they meet mainly in ICC/Asia Cup events."),
("sports",2,"The Asia Cup 2023 in cricket was won by:","India",["Pakistan","Sri Lanka","Bangladesh"],"India beat Sri Lanka in the final held in Colombo (hybrid model)."),
]
