# ga_facts_2.py — Polity (45) + Economics (35) + J&K Special (60)
FACTS = [
# ---------------- POLITY ----------------
("polity",1,"Who is known as the Father of the Indian Constitution?","Dr. B.R. Ambedkar",["Jawaharlal Nehru","Rajendra Prasad","Sardar Patel"],"Ambedkar chaired the Drafting Committee of the Constituent Assembly."),
("polity",1,"The Indian Constitution was adopted on:","26 November 1949",["26 January 1950","15 August 1947","9 December 1946"],"Adopted 26 Nov 1949 (Constitution Day); commenced 26 Jan 1950."),
("polity",2,"The President of India is elected by:","An electoral college through proportional representation",["Direct vote of citizens","Lok Sabha only","The Supreme Court"],"Elected MPs and MLAs elect the President by single transferable vote — asked in 2022."),
("polity",1,"The minimum age to become President of India is:","35 years",["30 years","25 years","40 years"],"President/Vice-President: 35; Lok Sabha MP/MLA: 25; Rajya Sabha MP/MLC: 30."),
("polity",1,"Fundamental Rights are contained in which Part of the Constitution?","Part III",["Part IV","Part II","Part V"],"Part III (Articles 12–35); Part IV holds Directive Principles."),
("polity",2,"Right to Constitutional Remedies falls under which Article?","Article 32",["Article 21","Article 19","Article 14"],"Ambedkar called Article 32 the 'heart and soul' of the Constitution."),
("polity",1,"How many fundamental duties does the Constitution list?","11",["10","9","12"],"Ten added by the 42nd Amendment (1976); the 11th (education, 6–14 yrs) by the 86th (2002)."),
("polity",2,"The concept of Directive Principles was borrowed from:","Ireland",["USA","UK","Canada"],"DPSPs came from the Irish Constitution; Fundamental Rights from the USA."),
("polity",1,"Who administers the oath of office to the President of India?","Chief Justice of India",["Vice-President","Speaker","Prime Minister"],"The CJI (or senior-most SC judge) swears in the President."),
("polity",2,"Who administers the oath to the Lieutenant Governor of a UT?","Chief Justice of the High Court",["The President","Home Minister","Chief Secretary"],"The concerned High Court's Chief Justice administers the LG's oath — asked in 2022."),
("polity",1,"The Rajya Sabha's maximum strength is:","250",["245","238","260"],"Up to 238 elected + 12 nominated = 250; current strength 245."),
("polity",1,"The Lok Sabha's maximum strength as per the Constitution is:","552",["545","550","560"],"530 states + 20 UTs + (formerly 2 nominated Anglo-Indians) = 552."),
("polity",2,"Money Bills can be introduced only in:","Lok Sabha",["Rajya Sabha","Either House","A joint sitting"],"Article 110: Money Bills start in Lok Sabha with the President's recommendation; RS can only suggest changes."),
("polity",2,"A joint sitting of Parliament is presided over by:","Speaker of the Lok Sabha",["President","Vice-President","Senior-most MP"],"Article 108: the Speaker chairs joint sittings."),
("polity",1,"The Vice-President of India is the ex-officio chairman of:","Rajya Sabha",["Lok Sabha","NITI Aayog","Election Commission"],"Article 64 makes the VP the Rajya Sabha Chairman."),
("polity",2,"Under which Article can the President declare a National Emergency?","Article 352",["Article 356","Article 360","Article 370"],"352: national; 356: President's rule in a state; 360: financial emergency."),
("polity",2,"President's Rule in a state is imposed under Article:","356",["352","360","365"],"Article 356 — failure of constitutional machinery in a state."),
("polity",1,"The writ of Habeas Corpus protects:","Personal liberty against illegal detention",["Property rights","Voting rights","Press freedom"],"'Produce the body' — courts order release of an unlawfully detained person."),
("polity",2,"Which writ commands a public official to perform a duty?","Mandamus",["Certiorari","Quo Warranto","Prohibition"],"Mandamus = 'we command'; Quo Warranto questions authority to hold office."),
("polity",1,"Panchayati Raj institutions received constitutional status through which amendment?","73rd Amendment (1992)",["74th Amendment","42nd Amendment","61st Amendment"],"73rd: panchayats; 74th: urban local bodies (municipalities)."),
("polity",2,"The 42nd Amendment (1976) added which words to the Preamble?","Socialist, Secular and Integrity",["Sovereign and Republic","Justice and Liberty","Democratic and Fraternity"],"The 'mini-Constitution' inserted socialist, secular, and integrity."),
("polity",1,"Voting age in India was lowered from 21 to 18 by which amendment?","61st Amendment (1988)",["42nd","44th","73rd"],"The 61st Amendment enfranchised 18-year-olds."),
("polity",2,"The Chief Election Commissioner is appointed by:","The President",["The Prime Minister","Parliament","The CJI"],"The President appoints the CEC/ECs; the CEC is removable like an SC judge."),
("polity",1,"The Supreme Court of India was established in its present form in:","1950",["1947","1935","1958"],"It replaced the Federal Court on 28 January 1950."),
("polity",2,"Judges of the Supreme Court retire at the age of:","65 years",["62 years","60 years","70 years"],"SC judges: 65; High Court judges: 62."),
("polity",1,"Who is the supreme commander of the Indian Armed Forces?","The President",["The Prime Minister","Defence Minister","Chief of Defence Staff"],"Article 53 vests supreme command in the President."),
("polity",2,"The Attorney-General of India is appointed under Article:","76",["78","88","110"],"The AG is the government's chief legal advisor with a right of audience in all courts."),
("polity",1,"'We, the People of India' are the opening words of the:","Preamble",["Fundamental Rights","Article 1","Oath of office"],"The Preamble declares popular sovereignty."),
("polity",2,"India is described in Article 1 as a:","Union of States",["Federation of States","Confederation","Unitary State"],"Ambedkar preferred 'Union' — states cannot secede."),
("polity",1,"The Panchayat's term is ______ years.","5",["4","6","3"],"Five years; fresh elections within six months of dissolution."),
("polity",2,"The Finance Commission is constituted every ______ years under Article 280.","5",["4","6","10"],"It recommends Centre–State tax sharing."),
("polity",2,"Which schedule of the Constitution lists the recognised languages?","Eighth Schedule",["Seventh","Ninth","Tenth"],"The 8th Schedule lists 22 languages, including Kashmiri and Dogri."),
("polity",2,"Kashmiri and Dogri appear in which Schedule of the Constitution?","Eighth Schedule",["Fifth","Sixth","Ninth"],"Both are among the 22 scheduled languages."),
("polity",2,"The anti-defection law is contained in which Schedule?","Tenth Schedule",["Eighth","Ninth","Twelfth"],"Added by the 52nd Amendment (1985)."),
("polity",1,"The Seventh Schedule of the Constitution deals with:","Division of powers (Union, State, Concurrent lists)",["Languages","Oaths","Panchayats"],"Union list ~100 subjects, State ~61, Concurrent ~52."),
("polity",1,"Police and Public Order fall in which list?","State List",["Union List","Concurrent List","Residuary"],"Policing is a state subject — but in UTs like J&K it rests with the LG/Centre."),
("polity",2,"Under the J&K Reorganisation Act, police and public order in J&K UT are controlled by:","The Lieutenant Governor (Centre)",["The elected Assembly","The High Court","The Mayor"],"In the UT of J&K, 'police' and 'public order' vest with the LG, not the elected government."),
("polity",1,"Article 21 of the Constitution guarantees:","Protection of life and personal liberty",["Equality before law","Freedom of religion","Right to property"],"'No person shall be deprived of his life or personal liberty except according to procedure established by law.'"),
("polity",1,"Right to Equality is guaranteed under Articles:","14 to 18",["19 to 22","23 to 24","25 to 28"],"Article 14: equality before law; 15: no discrimination; 16: equal opportunity; 17: untouchability abolished; 18: no titles."),
("polity",2,"Article 239A, relevant to J&K's UT structure, provides for:","Legislatures for certain Union Territories",["Financial emergency","High Courts for UTs","Special officer for minorities"],"UTs like Puducherry and J&K get legislatures via Article 239A — asked in 2022."),
("polity",2,"The quorum to conduct business in Lok Sabha is:","One-tenth of total membership",["One-fourth","Half","Two-thirds"],"Article 100: quorum is 1/10th of the House."),
("polity",1,"Who appoints the Governor of a state?","The President",["Chief Minister","Parliament","The CJI"],"Governors are appointed by the President for five years (pleasure doctrine)."),
("polity",2,"The First Amendment to the Indian Constitution (1951) is related to:","Land reforms and restrictions on free speech (Ninth Schedule)",["Abolition of privy purses","Emergency powers","Panchayati raj"],"It created the Ninth Schedule shielding land-reform laws."),
("polity",1,"The Comptroller and Auditor General (CAG) audits:","Government accounts",["Private companies","Political parties","Cooperative shops"],"CAG (Article 148) is the guardian of the public purse."),
("polity",2,"'Secular' in the Indian context means:","The State treats all religions equally",["The State promotes one religion","Religion is banned","Only minorities are protected"],"Positive secularism: equal respect, no state religion."),

# ---------------- ECONOMICS ----------------
("economics",1,"The Reserve Bank of India was established in:","1935",["1947","1950","1929"],"RBI began 1 April 1935; nationalised in 1949."),
("economics",1,"Who presents the Union Budget in Parliament?","The Finance Minister",["The President","The Prime Minister","RBI Governor"],"The FM presents it in Lok Sabha, usually on 1 February."),
("economics",2,"GST was rolled out across India on:","1 July 2017",["1 April 2016","1 January 2018","15 August 2017"],"'One nation, one tax' launched at midnight, 1 July 2017."),
("economics",2,"Which body replaced the Planning Commission in 2015?","NITI Aayog",["Finance Commission","Economic Advisory Council","SEBI"],"NITI Aayog is the government's policy think tank."),
("economics",1,"The currency of India is issued (except ₹1 note) by:","Reserve Bank of India",["Finance Ministry","SBI","NABARD"],"RBI issues notes; the ₹1 note bears the Finance Secretary's signature."),
("economics",2,"'Repo rate' is the rate at which:","RBI lends to commercial banks",["Banks lend to RBI","Banks lend to customers","RBI lends to the government"],"Repo = RBI→banks lending rate; reverse repo is the opposite."),
("economics",2,"Inflation measured by the basket of retail consumer goods is called:","CPI (Consumer Price Index)",["WPI","GDP deflator","IIP"],"CPI tracks retail prices; WPI tracks wholesale."),
("economics",1,"GDP stands for:","Gross Domestic Product",["Gross Development Programme","General Domestic Price","Gross Deposit Product"],"The market value of all final goods and services produced within a country in a period."),
("economics",2,"The 'Green Revolution' in India is associated with:","M.S. Swaminathan",["Verghese Kurien","C. Subramaniam only","Norman Borlaug only"],"Swaminathan led India's HYV wheat-rice revolution (with Borlaug's varieties); Kurien led the White (milk) Revolution."),
("economics",2,"Operation Flood is related to:","Milk production",["Wheat","Fisheries","Irrigation"],"Kurien's Operation Flood made India the world's largest milk producer."),
("economics",1,"The headquarters of the RBI is in:","Mumbai",["New Delhi","Kolkata","Chennai"],"RBI HQ moved from Kolkata to Mumbai in 1937."),
("economics",2,"Which sector contributes the largest share to India's GDP?","Services",["Agriculture","Manufacturing","Mining"],"Services contribute over half of GDP; agriculture employs the most people."),
("economics",2,"'Fiscal deficit' means:","Government spending exceeding total receipts excluding borrowings",["Trade gap with other countries","Bank losses","Fall in forex reserves"],"It is bridged by government borrowing."),
("economics",1,"NABARD is the apex bank for:","Agriculture and rural development",["Exports","Housing","Industry"],"Set up in 1982 to refinance rural credit."),
("economics",2,"SEBI regulates:","The securities/stock market",["Banking","Insurance","Telecom"],"SEBI (1992, statutory) protects investors; IRDAI covers insurance."),
("economics",1,"The Mahatma Gandhi National Rural Employment Guarantee Act guarantees how many days of work?","100 days",["120 days","90 days","150 days"],"MGNREGA (2005) guarantees 100 days of wage employment per rural household."),
("economics",2,"'PM-KISAN' scheme provides farmers:","₹6,000 per year in three instalments",["Free electricity","₹12,000 per year","Crop insurance only"],"₹2,000 × 3 instalments directly into farmer accounts."),
("economics",2,"Ayushman Bharat PM-JAY provides health cover of:","₹5 lakh per family per year",["₹1 lakh","₹2 lakh","₹10 lakh"],"The world's largest publicly funded health-assurance scheme."),
("economics",1,"The one-rupee note bears the signature of:","Finance Secretary",["RBI Governor","Finance Minister","President"],"All other notes carry the RBI Governor's signature."),
("economics",2,"India's foreign exchange reserves are managed by:","RBI",["SBI","Finance Ministry","SEBI"],"RBI holds and manages forex, gold and SDRs."),
("economics",1,"'Make in India' initiative was launched in:","2014",["2010","2016","2019"],"Launched September 2014 to boost manufacturing."),
("economics",2,"The base year currently used for India's GDP calculation is:","2011-12",["2004-05","2015-16","2001-02"],"GDP series shifted to base 2011-12 in January 2015."),
("economics",2,"Direct Benefit Transfer (DBT) aims to:","Send subsidies straight to beneficiaries' bank accounts",["Increase bank interest","Tax the rich directly","Give loans to states"],"DBT cuts leakages using Jan Dhan–Aadhaar–Mobile (JAM)."),
("economics",1,"The Jan Dhan Yojana is a scheme for:","Financial inclusion (bank accounts for all)",["Housing","Skill training","Crop insurance"],"PMJDY (2014) opened zero-balance accounts with RuPay cards."),
("economics",2,"Kashmir's economy leans most heavily on which sectors?","Horticulture, handicrafts and tourism",["Heavy industry","Mining","IT services"],"Apples, saffron, pashmina/carpets and tourism drive the valley's economy."),
("economics",2,"The GI tag protects:","Products linked to a specific geographic origin",["All Indian brands","Patents on machines","Film titles"],"E.g., Kashmir saffron, Kani shawls, Basohli paintings hold GI tags."),
("economics",1,"India's financial year runs from:","1 April to 31 March",["1 January to 31 December","1 July to 30 June","1 March to 28 February"],"Budget and accounts follow the April–March year."),
("economics",2,"'Disinvestment' means:","Selling government stake in public sector firms",["Banning investment","Foreign investment inflow","Closing loss-making banks"],"The government dilutes PSU equity to raise resources."),
("economics",2,"Which tax replaced many indirect taxes like VAT, excise and service tax?","GST",["Income tax","Wealth tax","Customs duty"],"GST subsumed 17 indirect taxes into one destination-based tax."),
("economics",1,"The currency symbol ₹ was designed by:","D. Udaya Kumar",["R.K. Joshi","Nandan Nilekani","A.P.J. Abdul Kalam"],"Adopted in 2010, blending Devanagari 'Ra' and Roman 'R'."),
("economics",2,"'Startup India' primarily supports:","New entrepreneurial ventures",["Old PSUs","Farm subsidies","Housing loans"],"Launched 2016: tax breaks, easier compliance, funding support."),
("economics",2,"UDAN scheme is related to:","Affordable regional air connectivity",["Rural roads","Digital literacy","Solar power"],"Ude Desh ka Aam Nagrik connects small airports at capped fares."),
("economics",1,"The largest source of tax revenue for the Government of India is:","GST/Income & corporation taxes (direct+indirect mix — GST largest single indirect)",["Customs only","Wealth tax","Stamp duty"],"Income+corporation tax lead direct taxes; GST dominates indirect collections."),
("economics",2,"Amul is associated with which cooperative model state?","Gujarat",["Punjab","Maharashtra","Karnataka"],"Anand (Gujarat) dairy cooperative inspired Operation Flood."),
("economics",2,"'Har Ghar Nal Se Jal' relates to which mission?","Jal Jeevan Mission",["Swachh Bharat","AMRUT","PM Awas"],"Piped drinking water to every rural household."),

# ---------------- J&K SPECIAL ----------------
("jk",1,"The J&K Reorganisation Act came into effect on which date (appointed day)?","31 October 2019",["5 August 2019","26 January 2020","15 August 2019"],"Parliament passed it in August; the two UTs were born on 31 October 2019 (Sardar Patel's birth anniversary)."),
("jk",1,"The J&K Reorganisation Act 2019 created which two Union Territories?","J&K (with legislature) and Ladakh (without legislature)",["J&K and Kargil","Jammu and Kashmir as separate UTs","J&K and Gilgit"],"J&K UT got an assembly; Ladakh UT (Leh + Kargil) did not."),
("jk",2,"Article 370 of the Constitution was effectively abrogated on:","5 August 2019",["31 October 2019","26 January 2019","15 August 2020"],"Presidential Order C.O. 272 and the Rajya Sabha resolution came on 5 August 2019."),
("jk",2,"Article 35A, scrapped in 2019, had dealt with:","Special rights of J&K's 'permanent residents'",["J&K's flag","The LoC","Land ceilings across India"],"It let the J&K legislature define permanent residents and their exclusive rights."),
("jk",1,"The number of seats in the J&K Legislative Assembly after delimitation (2022) is:","90",["83","87","111"],"Jammu 43 + Kashmir 47 = 90 (plus reserved PoJK seats kept vacant)."),
("jk",2,"The 2022 Delimitation Commission for J&K was headed by:","Justice (Retd.) Ranjana Prakash Desai",["Justice Lokur","Sushil Chandra","Justice Sikri"],"The Desai Commission redrew constituencies, adding 6 Jammu and 1 Kashmir seat."),
("jk",1,"Who was appointed the first Lieutenant Governor of the UT of J&K?","Girish Chandra Murmu",["Manoj Sinha","Satya Pal Malik","R.K. Mathur"],"Murmu took office 31 Oct 2019; Manoj Sinha succeeded him in August 2020."),
("jk",1,"The first Lieutenant Governor of the UT of Ladakh was:","R.K. Mathur",["G.C. Murmu","B.D. Mishra","Radha Krishna"],"Mathur was sworn in at Leh on 31 October 2019."),
("jk",1,"The last Governor of the undivided state of J&K was:","Satya Pal Malik",["N.N. Vohra","G.C. Murmu","Jagmohan"],"Malik oversaw the 2019 transition; before him N.N. Vohra served a decade."),
("jk",2,"J&K's own state constitution (of 1957) stood ______ after the 2019 changes.","Inoperative",["Strengthened","Partially retained for land laws","Converted into UT law"],"With Article 370 gone, the J&K Constitution and separate flag ceased to operate."),
("jk",1,"The high court serving both UTs is called:","High Court of Jammu & Kashmir and Ladakh",["Srinagar High Court","Northern High Court","J&K Federal Court"],"Renamed in 2020, it serves both UTs with wings at Jammu and Srinagar."),
("jk",1,"Under the UT scheme, who is the executive head of J&K?","Lieutenant Governor",["Governor","Chief Secretary","President directly"],"The LG administers J&K aided by the council of ministers (when an assembly exists)."),
("jk",2,"How many Lok Sabha seats does the UT of J&K have?","5",["6","4","3"],"Baramulla, Srinagar, Anantnag-Rajouri, Udhampur, Jammu; Ladakh has its own 1."),
("jk",2,"How many Rajya Sabha seats does J&K UT have?","4",["2","6","5"],"J&K retains 4 Rajya Sabha seats; Ladakh has none."),
("jk",1,"The winter capital of J&K is:","Jammu",["Srinagar","Udhampur","Katra"],"Under the Darbar Move tradition, Jammu (winter) and Srinagar (summer) alternate as seats of government."),
("jk",2,"The centuries-old 'Darbar Move' practice was discontinued in:","2021",["2019","2016","2023"],"The administration ended the biannual full-scale office shift in June 2021 after e-office adoption."),
("jk",1,"The official languages of J&K UT under the 2020 Act are:","Kashmiri, Dogri, Urdu, Hindi and English",["Urdu and English only","Kashmiri and Hindi only","Dogri, Punjabi, Urdu"],"The J&K Official Languages Act 2020 lists five official languages."),
("jk",2,"Before 2020, the sole official language of J&K state had been:","Urdu",["Kashmiri","Persian","Hindi"],"Urdu served as the official language from Dogra times until the 2020 Act."),
("jk",1,"The J&K Police's highest gallantry-linked identity — its motto — is:","'Duty and Honour' (Farz aur Nishan)",["'Satyameva Jayate'","'Service Before Self'","'Veerta aur Vivek'"],"J&K Police functions under the LG's Home Department with the ethos of duty and honour."),
("jk",1,"The Sher-i-Kashmir Police Academy, where SIs are trained, is at:","Udhampur",["Srinagar","Kathua","Anantnag"],"SKPA Udhampur is J&K Police's premier training institution."),
("jk",2,"The rank of Sub-Inspector in J&K Police is directly above:","Assistant Sub-Inspector (ASI)",["Head Constable","Inspector","Constable"],"Order: Constable → Head Constable → ASI → SI → Inspector."),
("jk",2,"A Sub-Inspector posted as officer in charge of a police station is commonly called:","SHO (Station House Officer)",["SDPO","DySP","Reader"],"The SHO heads a police station; in cities an Inspector may hold the charge."),
("jk",1,"The 'Chinar' tree, symbol of Kashmir, is botanically:","Platanus orientalis",["Cedrus deodara","Pinus wallichiana","Juglans regia"],"The oriental plane (booune in Kashmiri) turns flame-red each autumn — J&K's heritage tree."),
("jk",1,"The state animal of J&K (UT) is:","Hangul (Kashmir stag)",["Snow leopard","Markhor","Ibex"],"The hangul survives mainly in Dachigam NP; the snow leopard is Ladakh's."),
("jk",1,"The bird adopted as the UT symbol of J&K after 2019 is:","Kashmir flycatcher",["Peacock","Black-necked crane","Himalayan monal"],"J&K adopted the Kashmir flycatcher; the black-necked crane is Ladakh's UT bird."),
("jk",2,"Which lake in Srinagar hosts the famous floating vegetable market?","Dal Lake",["Wular","Manasbal","Anchar"],"Dal's early-morning floating market sells produce from its floating gardens (raad)."),
("jk",2,"The floating gardens of Dal Lake are locally called:","Raad",["Karewa","Demb","Nambal"],"Vegetables grow on these floating mats of weeds and soil."),
("jk",1,"Shikara is:","A traditional wooden boat of Dal Lake",["A woollen shawl","A Kashmiri bread","A mountain pass"],"The gondola-like shikara ferries tourists and traders on Dal."),
("jk",2,"The world-famous 'Kani' shawls come from which town?","Kanihama (Budgam)",["Sopore","Pampore","Kishtwar"],"Kani weaving with wooden bobbins holds a GI tag; Kanihama village gives the name."),
("jk",1,"Habba Khatoon, the 16th-century poet-queen of Kashmir, was the wife of:","Yusuf Shah Chak",["Zain-ul-Abidin","Shah Mir","Akbar"],"The 'Nightingale of Kashmir' composed lol lyrics; a Gurez peak bears her name."),
("jk",2,"The Mughal Road connects Shopian in the valley with:","Poonch/Rajouri (via Peer Ki Gali)",["Kishtwar","Doda","Leh"],"The historic route over Pir Panjal was used by Mughal emperors to enter Kashmir."),
("jk",2,"Asia's largest tulip garden in Srinagar sits at the foothills of:","Zabarwan range",["Pir Panjal","Harmukh","Apharwat"],"The Indira Gandhi Tulip Garden overlooks Dal beneath the Zabarwan hills."),
("jk",1,"The famous winter sports destination Gulmarg has which cable car?","Gulmarg Gondola",["Apharwat Express","Khilanmarg Ropeway","Pir Panjal Cable"],"One of the world's highest gondolas, rising toward Apharwat peak."),
("jk",2,"The Amarnath Yatra's twin base camps are Pahalgam and:","Baltal",["Sonamarg town","Kokernag","Aru"],"Baltal (Ganderbal) offers the shorter, steeper route to the cave."),
("jk",2,"Which festival marks the Kashmiri Pandit dedication to goddess at Kheer Bhawani temple?","Mela Kheer Bhawani (Zyeath Atham)",["Navreh","Herath","Baisakhi"],"Held at Tulmulla (Ganderbal) on Jyeshtha Ashtami; the spring's changing colours are legendary."),
("jk",1,"Herath is the Kashmiri Pandit celebration of:","Maha Shivratri",["Diwali","Holi","Janmashtami"],"Herath (Har-ratri) is the valley Pandits' biggest festival, with walnuts and 'vatuk' worship."),
("jk",2,"The J&K Bank was founded in which year?","1938",["1947","1956","1926"],"Founded by Maharaja Hari Singh's government; HQ in Srinagar."),
("jk",1,"The Srinagar–Jammu national highway is numbered:","NH-44",["NH-1A (old name still official)","NH-15","NH-3"],"The old NH-1A was renumbered NH-44 — India's longest N–S highway."),
("jk",2,"The USBRL rail project stands for:","Udhampur–Srinagar–Baramulla Rail Link",["Universal Srinagar Broadgauge Rail Line","Udhampur Southern Border Rail Link","Uri–Srinagar–Banihal Rail Link"],"The line through Chenab bridge and Banihal connects the valley to the Indian network."),
("jk",2,"Vande Bharat trains reached the Kashmir valley after the completion of:","The Chenab bridge & USBRL link (2025)",["Zoji La tunnel","Mughal road","Karakoram corridor"],"With USBRL complete, through trains connected Katra–Srinagar in 2025."),
("jk",1,"The Shri Mata Vaishno Devi Shrine Board was established under whose initiative in 1986?","Governor Jagmohan",["Sheikh Abdullah","Karan Singh","G.M. Shah"],"The SMVDSB manages the pilgrimage; Katra is the base town."),
("jk",2,"'Operation Sadbhavana' is run by:","The Indian Army in J&K",["J&K Police","CRPF","NDRF"],"The Army's goodwill schools, tours and infrastructure programme in border areas."),
("jk",1,"The LoC (Line of Control) divides:","Indian J&K/Ladakh from Pakistan-occupied areas",["India from China","Two J&K divisions","Kashmir valley from Jammu"],"Born of the 1972 Simla Agreement, replacing the 1949 ceasefire line."),
("jk",2,"The LAC (Line of Actual Control) in Ladakh separates India from:","China",["Pakistan","Afghanistan","Tajikistan"],"Eastern Ladakh (Galwan, Pangong) faces China across the LAC."),
("jk",2,"The Kartarpur-like cross-LoC bus 'Karwan-e-Aman' ran between Srinagar and:","Muzaffarabad",["Rawalpindi","Mirpur","Gilgit"],"Launched 2005 across the Kaman bridge at Uri; suspended in 2019."),
("jk",2,"Which pass on the LoC at Uri carries the 'Kaman Aman Setu'?","Kaman post on the Jhelum valley road",["Haji Pir","Sadhna pass","Razdan pass"],"The Kaman bridge was the crossing for the Srinagar–Muzaffarabad bus."),
("jk",1,"The J&K UT Foundation Day used to be celebrated on 31 October coinciding with:","Sardar Patel's birth anniversary (National Unity Day)",["Gandhi Jayanti","Constitution Day","Republic Day"],"The UTs were deliberately inaugurated on Rashtriya Ekta Diwas."),
("jk",2,"'Back to Village' (B2V) programme of J&K administration aims at:","Grassroots governance — officers visiting panchayats",["Tourism promotion","Border security","Handicraft exports"],"Gazetted officers camp in villages to deliver schemes and gather feedback."),
("jk",2,"The 'Mission Youth' initiative of J&K focuses on:","Youth engagement, livelihood and counselling",["Sports stadiums only","Army recruitment","School meals"],"Schemes like Mumkin (transport) and Tejaswini (women entrepreneurs) run under it."),
("jk",1,"Dogra Maharaja Ranbir Singh gave J&K which penal code?","Ranbir Penal Code (RPC)",["Indian Penal Code","Kashmir Codes","Dogra Danda Vidhi"],"RPC applied in J&K until 2019, when IPC replaced it under the Reorganisation Act."),
("jk",2,"After the 2019 reorganisation, crimes in J&K are prosecuted under:","IPC (now BNS) and central laws",["Ranbir Penal Code","J&K State Code","Sharia courts"],"Central laws replaced state codes; the RPC stood repealed."),
("jk",2,"The apex tourism body slogan for J&K has long been:","'Paradise on Earth'",["'God's Own Country'","'Incredible Hills'","'Crown of India'"],"Kerala uses 'God's Own Country'; Kashmir markets itself as Paradise on Earth."),
("jk",1,"Katra town serves as the base camp for:","Vaishno Devi yatra",["Amarnath yatra","Machail yatra","Buddha Amarnath"],"Katra (Reasi) is the railhead and starting point of the 12-km climb."),
("jk",2,"The Machail Mata yatra takes place in which district?","Kishtwar",["Doda","Reasi","Poonch"],"The Chandi pilgrimage runs to Machail village in Paddar, Kishtwar."),
("jk",2,"Which J&K district was carved out with headquarters at Shopian?","Shopian",["Kulgam","Pulwama","Budgam"],"Shopian, the apple bowl on the Mughal road, became a district in 2007."),
("jk",1,"The saffron town Pampore falls in which district?","Pulwama",["Srinagar","Anantnag","Budgam"],"Pulwama district holds the karewa saffron fields."),
("jk",2,"Which wetland near Srinagar, called the 'queen of wetlands', is a Ramsar site?","Hokersar",["Manasbal","Gil sar","Khushal sar"],"Hokersar is a Ramsar-listed migratory-bird habitat; Wular and Surinsar-Mansar are also Ramsar sites."),
("jk",2,"Wular Lake was designated under which international convention?","Ramsar Convention (wetlands)",["UNESCO Heritage","CITES","Basel Convention"],"Wular is a Ramsar wetland of international importance since 1990."),
("jk",1,"Which valley in Bandipora district is known as 'Gurez'?","Kishanganga valley segment with Dawar as HQ",["Lolab","Bangus","Betaab"],"Gurez, beyond Razdan pass, lies on the Kishanganga with Habba Khatoon peak."),
("jk",2,"The Lolab valley, 'land of love and beauty', is in district:","Kupwara",["Baramulla","Bandipora","Budgam"],"Lolab adjoins Kupwara; Bangus valley also lies in this district."),
("jk",2,"Which garden did Shah Jahan's governor Ali Mardan Khan NOT build — identify the Jahangir-era garden:","Shalimar Bagh",["Chashme Shahi","Achabal upgrades","Verinag pavilion"],"Shalimar (1619) is Jahangir's; Chashme Shahi (1632) came under Shah Jahan's reign."),
("jk",1,"Nishat Bagh, the 'garden of joy' on Dal Lake, was laid out by:","Asif Khan (Nur Jahan's brother)",["Jahangir himself","Dara Shikoh","Ali Mardan Khan"],"Asif Khan built Nishat in 1633; its twelve terraces face the lake."),
]
