# ga_facts_1.py — History (55) + Culture (30) + Geography (55)
# (topic, diff, question, correct, [3 distractors], explanation)
FACTS = [
# ---------------- HISTORY (India + J&K) ----------------
("history",1,"The Indus Valley Civilization site of Harappa lies on the bank of which river?","Ravi",["Indus","Sutlej","Ghaggar"],"Harappa was excavated on the Ravi; Mohenjo-daro is on the Indus."),
("history",1,"Who founded the Maurya Empire?","Chandragupta Maurya",["Ashoka","Bindusara","Chanakya"],"Chandragupta founded it (c. 321 BCE) with Chanakya's guidance; Ashoka was his grandson."),
("history",1,"The Kalinga War that transformed Ashoka was fought in which present-day state?","Odisha",["Bihar","Andhra Pradesh","West Bengal"],"Kalinga corresponds to modern Odisha — this appeared in the 2022 SI paper."),
("history",2,"Gandhara art flourished under which dynasty?","Kushana",["Maurya","Gupta","Chola"],"Gandhara's Greco-Buddhist art peaked under Kushana rulers, especially Kanishka — asked in 2022."),
("history",2,"Rajatarangini, the famous chronicle of Kashmir's kings, was written by:","Kalhana",["Jonaraja","Bilhana","Kshemendra"],"Kalhana wrote Rajatarangini ('River of Kings') in the 12th century — core J&K history fact."),
("history",2,"Which Mughal emperor built the Shalimar Bagh in Srinagar?","Jahangir",["Akbar","Shah Jahan","Aurangzeb"],"Jahangir laid Shalimar Bagh (1619) for Nur Jahan; he famously loved Kashmir."),
("history",1,"The Battle of Plassey (1757) was fought between the British and:","Siraj-ud-Daulah",["Tipu Sultan","Bahadur Shah","Mir Qasim"],"Clive defeated Nawab Siraj-ud-Daulah of Bengal at Plassey."),
("history",1,"Who is known as the 'Iron Man of India'?","Sardar Vallabhbhai Patel",["Jawaharlal Nehru","Subhas Chandra Bose","Bhagat Singh"],"Patel earned the title for integrating 560+ princely states."),
("history",2,"The Treaty of Amritsar (1846), which transferred Kashmir to Gulab Singh, was signed with:","The British East India Company",["The Sikh Empire","The Afghan Durranis","The Mughal court"],"After the First Anglo-Sikh War, the Company sold Kashmir to Dogra ruler Gulab Singh for 75 lakh rupees."),
("history",2,"Who was the last Dogra Maharaja of Jammu and Kashmir?","Hari Singh",["Gulab Singh","Ranbir Singh","Pratap Singh"],"Maharaja Hari Singh signed the Instrument of Accession to India on 26 October 1947."),
("history",1,"The Instrument of Accession of J&K to India was signed in which year?","1947",["1946","1948","1950"],"Signed 26 October 1947 after the tribal invasion; India then airlifted troops to Srinagar."),
("history",1,"The Quit India Movement was launched in:","1942",["1940","1930","1945"],"Gandhi's 'Do or Die' call came on 8 August 1942 in Bombay."),
("history",1,"Jallianwala Bagh massacre took place in which city?","Amritsar",["Lahore","Delhi","Ludhiana"],"On 13 April 1919, General Dyer fired on a peaceful gathering at Jallianwala Bagh, Amritsar."),
("history",2,"The Dandi March of 1930 was undertaken to protest the tax on:","Salt",["Land","Cotton","Tea"],"Gandhi marched 240 miles to Dandi to break the salt law."),
("history",2,"Annie Besant published which newspapers?","Commonweal and New India",["Kesari and Maratha","Young India and Harijan","Bande Mataram and Karmayogin"],"Besant ran 'Commonweal' and 'New India' — asked in the 2022 SI paper."),
("history",1,"Who gave the slogan 'Jai Jawan Jai Kisan'?","Lal Bahadur Shastri",["Jawaharlal Nehru","Indira Gandhi","Atal Bihari Vajpayee"],"Shastri coined it during the 1965 war to honour soldiers and farmers."),
("history",2,"The Constituent Assembly's membership after partition was reduced to:","299",["389","311","272"],"Partition brought it down from 389 to 299 — asked in the 2022 SI paper."),
("history",1,"Mahatma Gandhi was born in which year?","1869",["1867","1872","1875"],"Born 2 October 1869 at Porbandar, Gujarat."),
("history",2,"The first Battle of Panipat (1526) was fought between Babur and:","Ibrahim Lodi",["Rana Sanga","Hemu","Sher Shah"],"Babur's victory over Ibrahim Lodi founded the Mughal Empire."),
("history",2,"Sher Shah Suri is best remembered for building:","The Grand Trunk Road",["The Red Fort","The Qutub Minar","Fatehpur Sikri"],"Sher Shah rebuilt and extended the GT Road and introduced the rupiya coin."),
("history",1,"The capital of the Mauryan Empire was:","Pataliputra",["Taxila","Ujjain","Kannauj"],"Pataliputra (modern Patna) was the Mauryan capital."),
("history",2,"Kanishka's capital, closely linked with Kashmir's Buddhist history, was:","Purushapura (Peshawar)",["Mathura","Taxila","Kabul"],"Kanishka ruled from Purushapura; the 4th Buddhist Council was held in Kashmir under him."),
("history",2,"The Fourth Buddhist Council was held in Kashmir during the reign of:","Kanishka",["Ashoka","Harsha","Ajatashatru"],"Held at Kundalvan (Kashmir) c. 72 CE under Kanishka — a favourite J&K exam fact."),
("history",1,"Who was India's first Governor-General after independence?","Lord Mountbatten",["C. Rajagopalachari","Rajendra Prasad","Lord Wavell"],"Mountbatten stayed on till 1948; Rajagopalachari was the first Indian Governor-General."),
("history",1,"The Indian National Congress was founded in:","1885",["1875","1892","1905"],"Founded by A.O. Hume in Bombay, December 1885."),
("history",2,"The partition of Bengal (1905) was carried out by:","Lord Curzon",["Lord Ripon","Lord Dalhousie","Lord Minto"],"Curzon divided Bengal in 1905, sparking the Swadeshi movement; it was annulled in 1911."),
("history",2,"Who founded the Azad Hind Fauj (INA) in its most famous form?","Subhas Chandra Bose",["Bhagat Singh","Ras Behari Bose alone","Chandra Shekhar Azad"],"Bose reorganised and led the INA from 1943 with the call 'Give me blood, I will give you freedom.'"),
("history",1,"The Simon Commission (1928) was boycotted because:","It had no Indian member",["It raised taxes","It divided Punjab","It banned Congress"],"An all-white commission on Indian reforms provoked nationwide protests."),
("history",2,"Lala Lajpat Rai died of injuries received during a protest against:","The Simon Commission",["The Rowlatt Act","Salt laws","Partition of Bengal"],"He was lathi-charged at Lahore in 1928 protesting the Simon Commission."),
("history",1,"India's first President was:","Dr. Rajendra Prasad",["Dr. S. Radhakrishnan","C. Rajagopalachari","Zakir Husain"],"Rajendra Prasad served 1950–1962, the only President elected twice."),
("history",2,"The Dogra dynasty of Jammu was founded by:","Gulab Singh",["Hari Singh","Ranjit Singh","Zorawar Singh"],"Gulab Singh became Maharaja under the 1846 Treaty of Amritsar."),
("history",2,"General Zorawar Singh, the 'Napoleon of India', is famous for conquering:","Ladakh and Baltistan",["Sindh","Kabul","Punjab hills"],"The Dogra general annexed Ladakh (1834–40) and died in the Tibet campaign."),
("history",2,"Sultan Zain-ul-Abidin, the beloved ruler of Kashmir, was popularly called:","Budshah",["Lalitaditya","Shah Mir","Akbar of Kashmir"],"Zain-ul-Abidin (1420–70), 'Budshah' (great king), promoted crafts, tolerance and learning."),
("history",2,"Lalitaditya Muktapida, Kashmir's greatest ancient conqueror, belonged to which dynasty?","Karkota",["Utpala","Lohara","Shah Mir"],"The 8th-century Karkota king built the Martand Sun Temple."),
("history",2,"The Martand Sun Temple in Kashmir was built by:","Lalitaditya Muktapida",["Kalhana","Avantivarman","Harsha of Kashmir"],"Lalitaditya's 8th-century temple at Mattan (Anantnag) is J&K's most iconic ruin."),
("history",1,"Sheikh Mohammad Abdullah is associated with which political party?","National Conference",["PDP","Congress","Muslim League"],"He founded the All J&K Muslim Conference (1932), renamed National Conference in 1939."),
("history",1,"The Red Fort in Delhi was built by:","Shah Jahan",["Akbar","Aurangzeb","Humayun"],"Shah Jahan built it (1638–48) when he shifted the capital to Shahjahanabad."),
("history",1,"The Rowlatt Act was passed in the year:","1919",["1909","1929","1935"],"The 'Black Act' allowed detention without trial; it triggered the Jallianwala Bagh tragedy."),
("history",2,"Which Governor-General introduced the Doctrine of Lapse?","Lord Dalhousie",["Lord Wellesley","Lord Canning","Lord Hastings"],"Dalhousie annexed states without male heirs (Satara, Jhansi, Nagpur)."),
("history",1,"The Revolt of 1857 began from which place?","Meerut",["Delhi","Jhansi","Kanpur"],"Sepoys at Meerut rose on 10 May 1857 and marched to Delhi."),
("history",1,"Rani Lakshmibai was the queen of:","Jhansi",["Gwalior","Indore","Satara"],"She led the 1857 revolt in Jhansi and died fighting at Gwalior."),
("history",2,"The Ghadar Party was founded in 1913 at:","San Francisco",["Lahore","Berlin","London"],"Punjabi immigrants in the USA founded it to overthrow British rule."),
("history",2,"Who founded the Arya Samaj in 1875?","Swami Dayanand Saraswati",["Raja Ram Mohan Roy","Swami Vivekananda","Keshab Chandra Sen"],"Dayanand's slogan: 'Go back to the Vedas'."),
("history",1,"Raja Ram Mohan Roy founded which reform movement?","Brahmo Samaj",["Arya Samaj","Prarthana Samaj","Ramakrishna Mission"],"Founded 1828; he fought sati and championed modern education."),
("history",2,"The Gupta ruler known as the 'Napoleon of India' is:","Samudragupta",["Chandragupta II","Skandagupta","Kumaragupta"],"Historian V.A. Smith gave Samudragupta the title for his conquests."),
("history",2,"Nalanda University was destroyed by:","Bakhtiyar Khilji",["Mahmud of Ghazni","Muhammad Ghori","Timur"],"Khilji burned the great monastery-university around 1193 CE."),
("history",1,"The Azad Kashmir/tribal raid on Kashmir (Operation Gulmarg) began in which month-year?","October 1947",["August 1947","January 1948","June 1946"],"Pashtun tribal lashkars invaded on 22 October 1947, prompting the accession."),
("history",2,"The first Prime Minister (Wazir-e-Azam) of Jammu & Kashmir state after accession was:","Sheikh Mohammad Abdullah",["Mehr Chand Mahajan","Bakshi Ghulam Mohammad","G.M. Sadiq"],"Mahajan was the last PM under the Maharaja (till March 1948); Sheikh Abdullah headed the emergency administration and became PM in 1948."),
("history",2,"Delhi Agreement between Sheikh Abdullah and Nehru was signed in:","1952",["1947","1950","1957"],"The 1952 Delhi Agreement defined Centre–State relations for J&K."),
("history",1,"Mahatma Gandhi's first satyagraha in India was at:","Champaran",["Kheda","Ahmedabad","Dandi"],"The 1917 Champaran satyagraha supported indigo farmers in Bihar."),
("history",2,"Who among the following was NOT a moderate leader of Congress?","Bal Gangadhar Tilak",["Gopal Krishna Gokhale","Dadabhai Naoroji","Pherozeshah Mehta"],"Tilak belonged to the extremist trio Lal-Bal-Pal; the others were moderates."),
("history",1,"'Swaraj is my birthright and I shall have it' was declared by:","Bal Gangadhar Tilak",["Mahatma Gandhi","Bhagat Singh","Lala Lajpat Rai"],"Tilak's famous declaration became the nationalist rallying cry."),
("history",2,"The Kashmir valley's Shah Mir dynasty began in which century?","14th century",["12th century","16th century","10th century"],"Shah Mir became Sultan in 1339, founding Muslim rule in Kashmir."),
("history",2,"Amarnath cave shrine's annual yatra honours which deity?","Lord Shiva",["Lord Vishnu","Goddess Durga","Lord Ganesha"],"The ice lingam at Amarnath (Anantnag district) is sacred to Shiva."),
("history",1,"India became a Republic on:","26 January 1950",["15 August 1947","26 November 1949","30 January 1948"],"The Constitution commenced on 26 Jan 1950, chosen to honour the 1930 Purna Swaraj pledge."),

# ---------------- CULTURE ----------------
("culture",1,"Which craft is Kashmir world-famous for?","Pashmina shawls",["Madhubani painting","Blue pottery","Chikankari"],"Pashmina (cashmere) weaving is Kashmir's signature GI-tagged craft."),
("culture",2,"The famous spring festival of Kashmir celebrating almond blossoms at Badamwari is in:","Srinagar",["Jammu","Anantnag","Baramulla"],"Badamwari garden in old Srinagar hosts the almond-bloom festival each spring."),
("culture",1,"Rouf is a traditional folk dance of:","Kashmir",["Jammu","Rajasthan","Himachal"],"Rouf is danced by Kashmiri women in rows, especially on Eid and harvest."),
("culture",2,"'Wanvun' in Kashmiri culture refers to:","Traditional wedding songs",["A woollen blanket","A copper vessel","A boat race"],"Wanvun is the chorus singing at Kashmiri weddings."),
("culture",1,"The Dogri language is primarily spoken in which region?","Jammu",["Kashmir valley","Ladakh","Kargil"],"Dogri, an official language of J&K, is the mother tongue of the Jammu Dogras."),
("culture",2,"Kud is a folk dance of which region of J&K?","Jammu (Duggar region)",["Kashmir valley","Ladakh","Gurez"],"Kud is performed at night around fires in the Jammu hills to honour village deities."),
("culture",2,"The Hemis Festival, with masked Cham dances, is celebrated in:","Ladakh",["Kashmir","Jammu","Kishtwar"],"Hemis monastery's festival honours Guru Padmasambhava."),
("culture",1,"Kangri is a Kashmiri item used for:","Keeping warm (fire pot)",["Cooking rice","Carrying water","Storing grain"],"The kangri, an earthen pot in wicker, is carried under the pheran in winter."),
("culture",1,"Pheran is the traditional ______ of Kashmir.","Long winter gown",["Boat","Bread","Headgear"],"The loose pheran is worn by both men and women in the valley."),
("culture",2,"Wazwan, the multi-course royal cuisine, belongs to:","Kashmir",["Punjab","Awadh","Hyderabad"],"The 36-course wazwan (rista, rogan josh, gushtaba) is served at Kashmiri feasts."),
("culture",2,"The chief cook who prepares Wazwan is called:","Vasta Waza",["Khansama","Bawarchi","Mahara"],"The vasta waza heads the team of wazas at Kashmiri weddings."),
("culture",1,"Bhand Pather is a traditional form of ______ in Kashmir.","Folk theatre",["Carpet weaving","Boat making","Calligraphy"],"Bhand Pather is satirical folk theatre performed by travelling troupes."),
("culture",2,"The shrine of Sheikh Noor-ud-din Noorani (Nund Rishi) is at:","Charar-i-Sharief",["Hazratbal","Shopian","Kupwara"],"The patron saint of Kashmir's Rishi order rests at Charar-i-Sharief, Budgam."),
("culture",2,"Lal Ded, the famous 14th-century mystic poetess of Kashmir, composed:","Vakhs",["Ghazals","Dohas","Shrukhs"],"Lal Ded's four-line vakhs shaped Kashmiri language and Shaivite mysticism; Nund Rishi composed shrukhs."),
("culture",1,"The Hazratbal shrine in Srinagar is located on the bank of:","Dal Lake",["Wular Lake","Jhelum river","Nigeen only"],"Hazratbal, housing the holy relic Moi-e-Muqqadas, stands on Dal's western shore."),
("culture",1,"Vaishno Devi shrine is located in which district?","Reasi",["Jammu","Udhampur","Kathua"],"The Trikuta hills shrine falls in Reasi district; base camp is Katra."),
("culture",2,"The famous Sufi order that shaped Kashmir, founded by Mir Sayyid Ali Hamadani, is:","Kubrawiya",["Chishtiya","Naqshbandiya","Qadriya"],"Shah-i-Hamadan brought the Kubrawi order and Persian crafts to Kashmir in the 14th century."),
("culture",2,"Khanqah-e-Moula, the oldest Muslim shrine in Srinagar, stands on the bank of river:","Jhelum",["Sindh","Lidder","Doodhganga"],"Built 1395 for Shah-i-Hamadan on the Jhelum in old Srinagar."),
("culture",1,"Basohli painting, a famous miniature school, originated in:","Jammu region",["Kashmir valley","Ladakh","Punjab plains"],"Basohli (Kathua district) produced bold 17th-century Pahari miniatures."),
("culture",1,"Bharatanatyam is the classical dance of:","Tamil Nadu",["Kerala","Odisha","Andhra Pradesh"],"Bharatanatyam evolved in Tamil temples; Kathakali is Kerala's, Odissi is Odisha's."),
("culture",1,"The festival of Baisakhi mainly marks:","Harvest and Punjabi new year",["Victory of Rama","Birth of Krishna","End of monsoon"],"Baisakhi (13/14 April) marks the rabi harvest and Khalsa founding day."),
("culture",2,"Sonam Losar / Losar festival is the new year of:","Ladakhi Buddhists",["Kashmiri Pandits","Dogras","Gujjars"],"Losar is Ladakh's Buddhist new year with monastery rituals."),
("culture",2,"Navreh is the new year festival of:","Kashmiri Pandits",["Dogras","Ladakhis","Sikhs"],"Navreh (Chaitra) begins the Kashmiri Pandit lunar year; a thali of rice and items is viewed at dawn."),
("culture",1,"The GI-tagged 'Kashmir saffron' is grown mainly at:","Pampore",["Sopore","Kulgam","Uri"],"Pampore's karewa fields (Pulwama) grow the world's most prized saffron."),
("culture",2,"Kishtwar is famous for which product?","Saffron and sapphire",["Walnut wood only","Copperware","Silk"],"Kishtwar grows saffron and its Paddar mines yield famed blue sapphires."),
("culture",1,"The 'Mubarak Mandi' heritage palace complex is in:","Jammu",["Srinagar","Leh","Poonch"],"Mubarak Mandi was the seat of Dogra maharajas in Jammu city."),
("culture",2,"'Samavar' in Kashmiri households is used to:","Brew and serve traditional tea",["Store pickles","Grind spices","Warm beds"],"The brass samavar brews kahwa and noon chai."),
("culture",1,"Noon chai, the everyday Kashmiri drink, is characteristically:","Pink and salty",["Sweet and black","Green and sweet","White and sour"],"Noon (salt) chai gets its pink colour from soda and aeration."),
("culture",1,"Which Indian classical dance form comes from Kerala?","Kathakali",["Kuchipudi","Manipuri","Sattriya"],"Kathakali's elaborate masks and mudras are from Kerala."),
("culture",2,"The Tulip Garden of Srinagar, Asia's largest, is named after:","Indira Gandhi",["Jawaharlal Nehru","Rajiv Gandhi","Sheikh Abdullah"],"The Indira Gandhi Memorial Tulip Garden lies on the Zabarwan foothills by Dal Lake."),

# ---------------- GEOGRAPHY ----------------
("geography",1,"The Karakoram range lies in which part of the Indian subcontinent?","Northern J&K and Ladakh",["Himachal Pradesh","Sikkim","Arunachal"],"K2 and the great glaciers lie in the Karakoram across northern J&K–Ladakh — asked in 2022."),
("geography",1,"The Tropic of Cancer passes through which of these states?","West Bengal",["Punjab","Bihar","Himachal Pradesh"],"It bisects 8 states including Gujarat, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram — asked in 2022."),
("geography",1,"River Godavari originates in which state?","Maharashtra",["Karnataka","Telangana","Madhya Pradesh"],"It rises at Trimbakeshwar (Nashik) — the 'Dakshina Ganga' — asked in 2022."),
("geography",1,"Mount Everest is located in which range?","Great Himalayas (Himadri)",["Pir Panjal","Karakoram","Shiwaliks"],"Everest (8849 m) crowns the Great Himalayan range in Nepal."),
("geography",1,"The Jhelum river rises from which spring in Kashmir?","Verinag",["Kokernag","Achabal","Chashme Shahi"],"Verinag (Anantnag) is the traditional source of the Jhelum (Vyeth)."),
("geography",1,"Wular Lake, one of Asia's largest freshwater lakes, lies in district:","Bandipora",["Srinagar","Baramulla","Kupwara"],"The Jhelum feeds Wular in Bandipora district."),
("geography",2,"The Pir Panjal range separates the Kashmir valley from:","The Jammu region / outer plains",["Ladakh","Tibet","Gilgit"],"Pir Panjal walls the valley's south-west; Banihal & the tunnels pierce it toward Jammu."),
("geography",2,"The Zoji La pass connects the Kashmir valley with:","Ladakh (Dras)",["Jammu","Poonch","Gilgit"],"Zoji La on the Srinagar–Leh highway links Sonamarg to Dras."),
("geography",1,"Banihal Pass lies in which mountain range?","Pir Panjal",["Karakoram","Zanskar","Ladakh range"],"The Jawahar Tunnel and new T5 pierce the Pir Panjal at Banihal."),
("geography",2,"The Chenab river is formed by the confluence of Chandra and Bhaga at:","Tandi (Himachal Pradesh)",["Kishtwar","Akhnoor","Reasi"],"Chandra+Bhaga = Chandrabhaga (Chenab), joining at Tandi, then flowing through Kishtwar–Akhnoor."),
("geography",2,"Which river is called 'Tawi', on whose banks Jammu city stands?","Tawi",["Ravi","Ujh","Basantar"],"Jammu, the 'city of temples', sits on the Tawi, a Chenab tributary."),
("geography",1,"Dal and Nigeen are lakes located in:","Srinagar",["Anantnag","Pulwama","Ganderbal"],"Dal with its houseboats and Nigeen adjoin Srinagar city."),
("geography",2,"Tso Moriri and Pangong Tso are high-altitude lakes of:","Ladakh",["Kashmir valley","Kishtwar","Himachal"],"Both brackish lakes lie in Ladakh; Pangong extends into Tibet."),
("geography",2,"The Siachen Glacier lies in which range?","Karakoram",["Pir Panjal","Zanskar","Great Himalaya"],"Siachen, the world's highest battlefield, is in the eastern Karakoram."),
("geography",1,"K2 (Mount Godwin-Austen), the world's second highest peak, is in the:","Karakoram range",["Himalaya range","Hindu Kush","Zanskar range"],"K2 (8611 m) crowns the Karakoram."),
("geography",2,"Gulmarg, the famous ski resort, is in which district?","Baramulla",["Budgam","Kupwara","Srinagar"],"Gulmarg ('meadow of flowers') lies in Baramulla at ~2650 m."),
("geography",2,"Pahalgam, gateway of the Amarnath yatra, lies on which river?","Lidder",["Sindh","Jhelum","Rambiara"],"Pahalgam (Anantnag) straddles the Lidder, a Jhelum tributary."),
("geography",2,"Sonamarg lies in which district, on the Sindh river?","Ganderbal",["Bandipora","Anantnag","Kulgam"],"'Meadow of gold' is in Ganderbal on the Srinagar–Leh route."),
("geography",1,"Which is the largest district of J&K (UT) by area?","Kishtwar",["Jammu","Anantnag","Doda"],"Kishtwar (~7,737 km²) is the largest district of the J&K UT."),
("geography",1,"How many districts does the UT of Jammu & Kashmir have?","20",["18","22","14"],"10 in Kashmir division + 10 in Jammu division = 20."),
("geography",2,"The Banihal–Qazigund road tunnel pierces which range?","Pir Panjal",["Zanskar","Karakoram","Shiwalik"],"The 8.45-km Navyug (Qazigund) tunnel cut travel between Jammu and the valley."),
("geography",2,"Chenani–Nashri (Dr. Syama Prasad Mookerjee) tunnel is India's longest ______ tunnel when opened.","Road",["Rail","Metro","Canal"],"The 9.28-km tunnel on NH-44 (Udhampur–Ramban) opened in 2017."),
("geography",2,"The Chenab Rail Bridge, world's highest railway arch bridge, is in district:","Reasi",["Ramban","Udhampur","Doda"],"At 359 m above the Chenab, it anchors the USBRL line at Kauri, Reasi."),
("geography",1,"The Kashmir valley lies between the Pir Panjal and which range?","Great Himalayas",["Karakoram","Shiwaliks","Aravallis"],"The valley is a longitudinal trough between Pir Panjal and the Great Himalaya."),
("geography",2,"'Karewas' of Kashmir are best described as:","Lacustrine (lake-deposit) terraces",["Glacial peaks","Alpine meadows","River islands"],"Karewas are ancient lake/glacial deposits — ideal for saffron cultivation."),
("geography",1,"Which crop is the Kashmir valley's famous horticulture export?","Apple",["Wheat","Sugarcane","Cotton"],"J&K produces about three-quarters of India's apples."),
("geography",2,"Basmati rice of which J&K area holds a GI tag?","R.S. Pura (Jammu)",["Sopore","Pulwama","Kargil"],"R.S. Pura's basmati from the Jammu plains carries the GI tag."),
("geography",1,"The Indus river enters India (Ladakh) from:","Tibet (China)",["Afghanistan","Nepal","Pakistan"],"Rising near Mansarovar in Tibet, the Indus flows through Ladakh into Pakistan."),
("geography",2,"Which pass connects Leh with the Nubra valley?","Khardung La",["Zoji La","Banihal","Rohtang"],"Khardung La (~5359 m) is among the world's highest motorable passes."),
("geography",1,"The largest saltwater lagoon/lake in India is:","Chilika",["Wular","Sambhar","Pulicat"],"Chilika (Odisha) is Asia's largest brackish lagoon; Sambhar is the largest inland salt lake."),
("geography",1,"Which state has the longest coastline in India?","Gujarat",["Maharashtra","Tamil Nadu","Andhra Pradesh"],"Gujarat's coastline (~1600 km) is India's longest."),
("geography",1,"The Sundarbans delta is formed by the Ganga and which river?","Brahmaputra",["Godavari","Mahanadi","Kosi"],"The world's largest delta is built by Ganga–Brahmaputra."),
("geography",2,"Doodhpathri, an emerging tourist meadow, lies in district:","Budgam",["Kulgam","Shopian","Kathua"],"'Valley of milk' is Budgam's alpine meadow."),
("geography",2,"Bhaderwah, called 'Mini Kashmir', is in which district?","Doda",["Kishtwar","Ramban","Rajouri"],"Bhaderwah valley in Doda is famed for lavender and meadows."),
("geography",2,"The Suru and Zanskar are rivers of which region?","Ladakh/Kargil",["Kashmir valley","Jammu plains","Pir Panjal south"],"Suru (Kargil) and Zanskar feed the Indus."),
("geography",1,"Which is the highest peak of the Pir Panjal range in J&K vicinity?","Indrasan/Deo Tibba area peaks (Pir Panjal); in J&K, Tatakooti",["K2","Nanga Parbat","Nun"],"Within J&K's Pir Panjal, Tatakooti (~4725 m) is the notable highest; Nun-Kun belong to the Zanskar range."),
("geography",2,"Nun and Kun (7000+ m twin peaks) belong to which range?","Zanskar range",["Pir Panjal","Karakoram","Shiwalik"],"The Nun-Kun massif rises between Suru valley and Zanskar."),
("geography",1,"Kolahoi, the highest peak inside the Kashmir valley rim, feeds which glacier/river?","Lidder",["Sindh only","Kishanganga","Rambiara"],"Kolahoi (5425 m) glacier feeds the Lidder at Pahalgam."),
("geography",2,"The Kishanganga (Neelum) river joins the Jhelum near:","Muzaffarabad",["Baramulla","Uri","Sopore"],"Kishanganga flows through Gurez and joins Jhelum at Domel/Muzaffarabad."),
("geography",2,"Gurez valley lies along which river?","Kishanganga",["Lidder","Sindh","Poonch"],"Gurez (Bandipora) straddles the Kishanganga below Habba Khatoon peak."),
("geography",1,"India's only cold desert region lies in:","Ladakh",["Kashmir valley","Jammu","Himachal lowlands"],"Ladakh's high-altitude rain-shadow makes it a cold desert."),
("geography",1,"The Thar desert lies mainly in which state?","Rajasthan",["Gujarat","Punjab","Haryana"],"About 60% of the Thar is in Rajasthan."),
("geography",1,"Which planet is known as the Red Planet?","Mars",["Venus","Jupiter","Mercury"],"Iron-oxide dust gives Mars its red colour."),
("geography",2,"The saffron-growing karewa town of Pampore lies in district:","Pulwama",["Srinagar","Budgam","Anantnag"],"Pampore's karewas in Pulwama district grow GI-tagged saffron."),
("geography",2,"Which is the only J&K district sharing a border with both Pakistan and PoJK areas across LoC in the south-west (Chicken's Neck area)?","Akhnoor belt of Jammu district",["Kathua","Samba","Udhampur"],"The Akhnoor sector of Jammu district faces the international border and LoC junction."),
("geography",1,"The 'Paradise on Earth' quote 'Gar firdaus...' about Kashmir is attributed to:","Amir Khusrau/Jahangir (said of Kashmir)",["Kalidasa","Al-Beruni","Ibn Battuta"],"'If there is a paradise on earth, it is this' — recited by Jahangir about Kashmir (couplet of Amir Khusrau)."),
("geography",1,"Salal and Baglihar dams are built on which river?","Chenab",["Jhelum","Ravi","Indus"],"Salal (Reasi) and Baglihar (Ramban) are Chenab hydro projects."),
("geography",2,"The Uri and Lower Jhelum hydroelectric projects are on which river?","Jhelum",["Chenab","Sindh","Kishanganga"],"Uri-I & II sit on the Jhelum near the LoC in Baramulla."),
("geography",2,"Dachigam National Park, home of the hangul, is near:","Srinagar",["Jammu","Leh","Rajouri"],"Dachigam protects the endangered Kashmir stag (hangul), the UT's iconic animal."),
("geography",2,"The hangul (Kashmir stag) is a subspecies of:","Red deer (elk family)",["Antelope","Ibex","Musk deer"],"Hangul is Central Asia's only red-deer subspecies, found in Dachigam."),
("geography",1,"Hemis National Park in Ladakh is famous for:","Snow leopards",["Tigers","Lions","One-horned rhinos"],"Hemis has the world's densest snow-leopard population."),
("geography",1,"Which Indian state is called the 'Land of Five Rivers'?","Punjab",["Haryana","Sindh","Himachal"],"Punj-ab = five waters: Sutlej, Beas, Ravi, Chenab, Jhelum."),
("geography",2,"The Shiwalik (outer Himalaya) hills dominate which J&K districts?","Jammu, Samba, Kathua belt",["Srinagar-Budgam","Leh-Kargil","Kupwara-Bandipora"],"The southern Jammu districts sit on Shiwalik foothills."),
("geography",1,"India's capital New Delhi lies on the bank of which river?","Yamuna",["Ganga","Sutlej","Chambal"],"Delhi grew along the Yamuna's right bank."),
]
